### ISSUE TITLE
Manual stop required in step mode if code incorrect

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#1003]
**What is the problem that you wish to solve? Please describe.**
When using step mode, the user has to manually stop the running code by pressing the stop button in the left-hand menu. This can be confusing to users.

**Describe the solution you'd like**
The code can still be modified whilst the step is in progress

**Describe alternatives you've considered**
A clearer indication of the control buttons

**Comment by mrniket** [comment]
This is confusing and annoying, but we can't fix anytime soon, so closing for now. We can reopen this later possibly.
