### ISSUE TITLE
Deleting workspace doesn't have any feedback and causes error

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1014]
**Describe the bug**
When deleting a workspace (ie a program in Blockly that a user has saved), there is no feedback to indicate whether the workspace is actually being deleted. The result also doesn't show, as in the user can wait as long as they want after clicking the delete button, the workspace isn't shown as deleted until the user refreshes the page.
If the user clicks the delete button a second time, a server connection error occurs (even though it's because the database can't find the workspace anymore).

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in to the website.
2. Go to the Rapid Router game, choose any level.
3. Add a couple of steps to your program in the game.
4. Navigate to the Save tab and save your workspace.
5. Navigate to the Delete tab.
6. Select your previously saved workspace and click Delete.
7. Wait a couple of seconds.
8. Observe that there is no feedback on the page, and the workspace seems to still be present.
9. Click Delete a second time.
10. Observe that a server connection error has occurred.
11. Navigate to any other tab.
12. Navigate back to the Delete tab.
13. Observe that your workspace has effectively been deleted.

**Expected behaviour**
When clicking the Delete button, the user should be able to see when the workspace has been deleted, ie the workspace needs to be removed from the list without having to refresh the page.
There also needs to be feedback right after clicking the Delete button. As such, if it takes a while to actually delete the workspace, the Delete button should be disabled to prevent users clicking it a second time and causing an error. There could also be an indicator that something is still happening (eg spinner). To be discussed with @j4mesholland.

**Screenshots**
Screen after clicking Delete a first time:
![delete_workspace2.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/323b3205-c778-4450-a194-6c38136b8e5c)

Screen after clicking Delete a second time:
![delete_workspace.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/3bb84d01-278a-43ea-9cde-a4d83c6a270e)

**Browsers**:
All

**Comment by faucomte97** [comment]
@sebp999 Just had a thought. Whenever you have some time, I wonder if this issue has been resolved by your previous on workspace saving & loading? Not a priority though :)

**Comment by sebp999** [comment]
No it still does that.  I'll have a look soon.
