### ISSUE TITLE
Repeated Level Names

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/rapid-router#1016]
**Describe the bug**
Levels 12 and 17 are both called "This road is more complicated and levels 26 and 70 are both called "Winter Wonderland"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.codeforlife.education/rapidrouter/
2. See problem

**Expected behaviour**
Levels should have different names.

**Screenshots**
<img width="300" alt="screenshot 2019-03-07 at 14 45 41" src="https://user-images.githubusercontent.com/30693435/53965799-c3ea9880-40e9-11e9-8f5a-5ede93e75eb9.png">
<img width="237" alt="screenshot 2019-03-07 at 14 45 52" src="https://user-images.githubusercontent.com/30693435/53965806-c6e58900-40e9-11e9-9b7e-378da9489451.png">
<img width="320" alt="screenshot 2019-03-07 at 14 58 33" src="https://user-images.githubusercontent.com/30693435/53965813-c947e300-40e9-11e9-9bbd-ad19bf7e6a40.png">
<img width="319" alt="screenshot 2019-03-07 at 14 58 58" src="https://user-images.githubusercontent.com/30693435/53965819-cbaa3d00-40e9-11e9-9545-8e0a90426678.png">

**Comment by mrniket** [comment]
We've looked at this, we think it's fine as the level number is the thing that makes it unique, if someone complains about we can raise this issue then. Closing for now
