### ISSUE TITLE
Rapid Router design system

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#1022]
## Description
We have some historical issues about the shortcomings of the existing game UI.

**We will need to build a design system:**
- Colours 
- Fonts
- Buttons
- Menus
- Overlays

Eradicate all unused and unlinked symbols and styles.

**Comment by lauracumming** [comment]
Issue moved to [ocadotechnology/codeforlife-design #2](https://github.com/ocadotechnology/codeforlife-design/issues/2) via [**ZenHub**](https://www.zenhub.com/)
