### ISSUE TITLE
Cypress integration 

### ISSUE THREAD

**Issue by JackD03** [ocadotechnology/rapid-router#1037]
## Task Description
Working on integrating cypress into the testing format for rapid router. These tests will be created so that individuals can refer to them when converting the selenium tests into cypress.

## Acceptance Criteria
- [ ] Cypress tests testing for different functionalities across Rapid Router created
- [ ] Figured out how to run Cypress tests in Travis

**Comment by mrniket** [comment]
Looks great! I'm going to close this until we have a discussion on how to take this further
