### ISSUE TITLE
Dragging blockly blocks does not work on a Windows 10 touch device

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/rapid-router#1040]
**Describe the bug**
Dragging blockly blocks does not work on a Windows 10 touch device

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [codeforlife.education/rapidrouter/2/](codeforlife.education/rapidrouter/2/)
2. Try to drag a blockly block with your finger
3. Observe that the block is not dragged

**Expected behaviour**
You should be able to drag a block with your finger

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Found on Firefox
 - Version 67.0.4

Also found on Chrome (75.0.3770.100), Firefox (67.0.4)and IE Edge (42.17134.10)

**Comment by faucomte97** [comment]
Fixed by #1042
