### ISSUE TITLE
Self-assessment sheets

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/rapid-router#1044]
Review the current self-assessment sheets for Rapid Router and generate a list of suggested changes/additions.

**Comment by rdcruzCFL** [comment]
[https://app.zenhub.com/files/18399425/0fc4681b-d590-45bf-9edb-8db7922dc7c3/download](https://app.zenhub.com/files/18399425/0fc4681b-d590-45bf-9edb-8db7922dc7c3/download)

This was what I wrote for end of KS2. Any initial thoughts?

**Comment by rdcruzCFL** [comment]
Looking at what is there, I would propose to make them all more concrete. Instead of just "I can do", add a level score or some sort of exercise so that they can show they can do it. I think this works better for all abilities and levels of confidence.

**Comment by rdcruzCFL** [comment]
I'm nearly there on these and should get them these finished this weekend - sorry for the delay.

**Comment by rdcruzCFL** [comment]
The KS2 document has the new column headers in it. These need to be added to the other self-assessment sheets so that a level can be linked in. 

- End of KS1:[https://app.zenhub.com/files/18399425/f34e3df1-412f-4497-8796-819f95cdc83c/download](https://app.zenhub.com/files/18399425/f34e3df1-412f-4497-8796-819f95cdc83c/download)

- End of KS2: https://app.zenhub.com/files/18399425/0fc4681b-d590-45bf-9edb-8db7922dc7c3/download

- Lower KS3: [https://app.zenhub.com/files/18399425/b221611c-5a42-4b53-a19b-d442cbbfcdd5/download](https://app.zenhub.com/files/18399425/b221611c-5a42-4b53-a19b-d442cbbfcdd5/download)

- Intermediate KS3: [https://app.zenhub.com/files/18399425/f7f1ee92-c2c8-4fb8-8bbd-00cbd9adce10/download](https://app.zenhub.com/files/18399425/f7f1ee92-c2c8-4fb8-8bbd-00cbd9adce10/download)

- Upper KS3: [https://app.zenhub.com/files/18399425/ee47f441-02df-4444-8953-99b77aff7333/download](https://app.zenhub.com/files/18399425/ee47f441-02df-4444-8953-99b77aff7333/download)

**Comment by mrniket** [comment]
Thanks for investigating this @rdcruzCFL! Closing this issue as the sheets have been reviewed

**Comment by faucomte97** [comment]
Reopening this for further investigation now that @lauracumming has joined the team :)

**Comment by faucomte97** [comment]
Superseded.
