### ISSUE TITLE
Teaching packs / Introduction to Coding Guide update

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/rapid-router#1061]
**Describe the bug**
The *Introduction to Coding Guide* is a mapping to the English National Curriculum. It is shown on the teaching packs page https://www.codeforlife.education/teach/materials/ but this is the mapping to the English National Curriculum only. The *Aligned to the Curriculum* section (https://www.codeforlife.education/teach/) shows a mapping to both the English and Scottish N/Cs.

Also, this *Introduction to Coding Guide* covers KS1 - KS3 but is in the KS1/2 section. 

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/2ec442d4-6a5f-49a4-9d00-0287b0e0e58a)

**Expected behaviour**
Perhaps there could just be a link back to the https://www.codeforlife.education/teach/ page between the User Guide and Key Stage 1, and Key Stage 2 and Key Stage 3 headings?
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/ed7e2d73-e527-4411-bc5b-02e054db4961)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]

**Additional context**

**Comment by dionizh** [comment]
Thanks @rdcruzCFL. Everything has been moved to Gitbook - so any review should be on the new layout on Gitbook.
