### ISSUE TITLE
Add documentation requirement in new task templates

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/rapid-router#1063]
## Task Description

Add `## Documentation Requirements` below the acceptance criteria. This is to make sure we think about what docs to write during task inception.

## Acceptance Criteria

- [ ] there is a documentation requirement/check in new task templates

## Copywrite Requirements

None

## Analytics Requirements

None

**Comment by dionizh** [comment]
A nice idea, but not sure about the practicalities of this. The task template hasn't been properly utilised too in other repos.
