### ISSUE TITLE
Upgrading Chromedriver caused Selenium test timeout error

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/rapid-router#1074]
**Describe the bug**
Chrome's latest version required an update to the chromedriver version, which in turn caused Travis tests to time out in PR #1073 . This was addressed by adding the parameter `wait_seconds` to the calls to the function `wait_for_element_to_be_invisible` and setting it to 15 seconds, and this seems to have slowed the tests down. Since it's outside the scope of the mentioned PR, this issue has been created to look further into it and how to speed Travis tests up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new branch
2. Remove `wait_seconds` argument on the calls to `wait_for_element_to_be_invisible` inside `editor_page.py` and `game_page.py`
2. Push changes
3. Create a new PR
4. See error in Travis build

**Expected behaviour**
This error doesn't show up locally, and it shouldn't happen when Travis runs the tests, either.

**Desktop (please complete the following information):**
 - Any

**Comment by mrniket** [comment]
@mariaFernando  is this still an issue?

**Comment by dionizh** [comment]
I think we still have occasional failure for Selenium tests, but this is specifically about Travis. There's also a plan to migrate Selenium tests to Cypress.
