### ISSUE TITLE
Remove django-foundation-icons and django-foundation-statics

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1079]
## Task Description
As part of the Python 3 upgrade, we want to remove [django-foundation-icons](https://github.com/benbacardi/django-foundation-icons) and [django-foundation-statics](https://github.com/benbacardi/django-foundation-statics).
The code is imported in game.scss however it seems like the code using it might be dead. Needs to be double-checked.

## Acceptance Criteria
- [ ] django-foundation-icons dependency removed.
- [ ] django-foundation-statics dependency removed.

**Comment by mrniket** [comment]
Upon further research, although the django-foundation-statics does not have the Python 3 classifier, it is Python 3 compatible. I tested this by using rapid router and portal in Python 3.6.7. Therefore the associated PR with this issue (#1083) only removes the icons.
