### ISSUE TITLE
Scoring issue reported

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1091]
39- 42 - if the pupil uses a general algorithm they can still score 20 out of 20 without using if statements and iteration.

**Comment by sebp999** [comment]
Current behaviour is that the number of coins depends only on the number of blocks in the solution.  For example, if the model solution has 5 blocks, and my solution has 5 blocks, then I get 10 coins.  However, apart from that, it doesn't take into account the quality of the solution, so it can't tell the difference between a solution that has if and iteration and a general solution.  There is some discussion about this at https://github.com/ocadotechnology/rapid-router/pull/1125.  Therefore this looks like it is part of a bigger task, redesigning the scoring algoritthm.

**Comment by razvan-pro** [comment]
Related to https://github.com/ocadotechnology/codeforlife-admin/issues/474
