### ISSUE TITLE
Increase size of avatar and pointer

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1095]
**Issue**
It is difficult to see avatars. 

Are we able to increase the size of the avatar a bit and the size of the pointer above the avatar?

**Comment by lauracumming** [comment]
The colour is also difficult to see and now the artefacts are yellow, they are lost even more.

**Comment by lauracumming** [comment]
Can we move this to AIMMO, please? I set it in RR by accident and it won't let me do it in Github. :(

**Comment by faucomte97** [comment]
Issue moved to [ocadotechnology/aimmo #1383](https://github.com/ocadotechnology/aimmo/issues/1383) via [**ZenHub**](https://www.zenhub.com/)
