### ISSUE TITLE
No scrollbar for Python pane

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1113]
**Describe the bug**
In levels 80+, when the Python code pane is introduced: there are no scrollbars in the pane to allow for scrolling in case the code goes beyond the size of the pane.

This was brought to our attention by a user ticket.

A current workaround is to zoom out.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 80.
2. Add blocks to the workspace until the Python code goes beyond the bottom of the Python pane.
3. Observe that there is no way to scroll up or down in the Python pane to see the lines that have gone beyond the screen.

**Expected behaviour**
There should be scrollbars similar to the Blockly and Map panes to allow the user to scroll and see the entirety of their code.

**Screenshots**
![Selection_092.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/adfa3c8d-2b11-4a53-9d8d-ccb02f50bb21)

**Comment by dionizh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/1113?planning-poker) with ZenHub @faucomte97 @KamilPawel
