### ISSUE TITLE
Rapid Router level creator - bin has stopped working

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1152]
**Describe the bug**
The bin seems to have moved to the corner of the screen and is not functioning. When creating levels, there isn't a way of deleting components that you add because of this. It should be on the actual map - bottom right.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'level_editor'
2. Click on 'scenery'
3. Add some components '....'
4. Try to delete - see bin is unavailable

**Expected behaviour**
Should be able to use bin
**Screenshots**
![Screenshot 2021-01-05 at 10.59.24.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/4ce1ceba-ccda-4c96-a1cb-f974fc5fc3c9)

**Desktop (please complete the following information):**
 - OS: [Macbook Pro]
 - Browser [Chrome]

**Comment by sebp999** [comment]
The issue was that the position of the trash is not set on page load, just on window resize.  Have made a pull request https://github.com/ocadotechnology/rapid-router/pull/1160
