### ISSUE TITLE
Empty help dialogue box

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/rapid-router#1185]
The help dialogue seems empty for levels 80-89. Not sure why. Needs investigating please.

![help.png](https://images.zenhubusercontent.com/601ac69612e543a2f4f6072d/b3c1e8d8-c069-4419-9474-e92440fa5472)

**Comment by sebp999** [comment]
The methods in game/messages.py return empty string, for example:
```
def hint_level82():
    return ""
```
Looking at git history, it looks as though they always have done, so I can't find any existing copy for them.  So we need to either 

- write some hints for them, or 
- check for empty string before displaying the modal or
- return `hint_level_default` if the `hint_level` method returns `""`

**Comment by dionizh** [comment]
@lauracumming Should we:
- add hint text, 
- fall back to default "Think back to earlier levels. What did you learn?", or
- disable/hide the hint button if there's no hint available
??

**Comment by SASRDCRUZ** [comment]
I am not sure it is very useful on the Python levels. The levels themselves have been seen before so the challenge is really about the Python. We could have a generic: "try using the blocks to solve this level and look at the Python code you are creating" for levels 80 - 91. but I am not sure what is useful thereafter. It's a modal window so we can't even show the Python syntax in it.

**Comment by rdcruzCFL** [comment]
I am not sure it is very useful on the Python levels. The levels themselves have been seen before so the challenge is really about the Python. We could have a generic: "try using the blocks to solve this level and look at the Python code you are creating" for levels 80 - 91. but I am not sure what is useful thereafter. It's a modal window so we can't even show the Python syntax in it.

**Comment by dionizh** [comment]
For Intro to Python levels (lv 80-91) - I added text that includes links to the Blockly guide and the python.org beginner’s guide.
For the Python levels (lv 92 onwards) - I added text to the existing hints that includes links to the Python commands and the python beginner’s guide.
Reviewed and approved by everyone.
