### ISSUE TITLE
document "general algorithm"

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1205]
The "general algorithm" is the algorithm around levels 30-40 approx. that uses repeat until at destination, go forward if road exists forward, else if road exists right, go right, etc...
The problem is that the algorithm isn't clearly defined anywhere and isn't really introduced or labelled as such in the game and in the lesson plans.
It also isn't clear when the levels try to show that the user cannot always rely on this algorithm to get the best solution.

The introductory texts, the hints, and the lesson plans need to make this clearer.

**Comment by lauracumming** [comment]
separate tasks have been created

**Comment by lauracumming** [comment]
_The code you have been using in the last few levels won't work here. Can you write something that still uses loops?_
