### ISSUE TITLE
Docker-ising rapid router

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/rapid-router#1210]
This is for dev and should work just like portal.

**Comment by mrniket** [comment]
Test comment

**Comment by mrniket** [comment]
I'll take this

**Comment by mrniket** [comment]
@dionizh Have you had this error recently? 

`django.db.utils.IntegrityError: The row in table 'common_teacher' with primary key '1' has an invalid foreign key: common_teacher.school_id contains a value '1' that does not have a corresponding value in portal_school.id.`

**Comment by dionizh** [comment]
Yes, I think this should be the same error: https://docs.codeforlife.education/git/common-issues#django-db-utils-integrityerror-on-mac
Let me know if that fixes it or not.

**Comment by mrniket** [comment]
Unfortunately it doesn't, the issue happens inside of the docker container so I couldn't use homebrew there. I did try: `RUN apt-get install -y sqlite3 libsqlite3-dev` but I still get the same error. I'll push my changes in the PR so you can see
