### ISSUE TITLE
Fix zoom bug

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1253]
Users are having difficulty using Rapid Router on a tablet. We need to disable the touch command on the game as users accidentally zoom when they don't want to and it causes chaos. We will be testing this in schools this term so we need to ensure tablet views are best possible.

Bug: When the zoom-out button is clicked, it initially zooms in! 🤯
Check top 2 OS and top 2 resolution

- [ ] disable touch for zoom
- [x] Move buttons to fit most most used tablet

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/1253?planning-poker) with Zenhub @KamilPawel @faucomte97

**Comment by faucomte97** [comment]
Half of this task has been done - the zoom buttons are now always visible and the game no longer randomly zooms in after any first input.
Still need to disable double-touch zoom though.
