### ISSUE TITLE
UKS3 session 15: n = 2; replace with number

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1317]
- [ ] Replace _n_ with _number_ in session 15 UKS3
- [ ] Worksheet to be updated too

**Comment by faucomte97** [comment]
https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit#

**Comment by SKairinos** [comment]
@evemartin completed this
