### ISSUE TITLE
Cow condition block and sound horn action block

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/rapid-router#1335]
This is a breakdown from task #952. We'd like the cow to act like a variation of traffic light, which potentially will be used for the Traffic Lights episode (lv 44-50). So we need to change the existing purple blocks to:

- Blue block that can be used with an if block. The block should say "cow" with the cow icon next to it.

- Green action block that says "sound horn" that can be used as an action like wait or move. The "sound horn" needs to chase away the cow. Note that this needs to work with brown and white cows. Please clean code as necessary. Only the visuals are different between the white and brown cows, the functionalities should be the same.

- Cow can appear at random time, but once appears, it needs to stay on the road until "sound horn" is performed on the cow.

**Comment by sebp999** [comment]
"If cows" is done.  "Sound horn" is mostly done, but doesn't chase the cows away yet.

**Comment by sebp999** [comment]
Sound horn can now chase away cows

**Comment by sebp999** [comment]
All works, for white cows.  I think we should merge with white cows only and get a feel for how that goes: brown cows are an embellishment and functionality is the same as far as I can tell.

**Comment by sebp999** [comment]
I think "sound horn" needs a yellow horn image but I don't know how to make svgs

**Comment by sebp999** [comment]
I have pushed the branch to a [PR](https://github.com/ocadotechnology/rapid-router/pull/1376) and requested review
