### ISSUE TITLE
Check and fix CFL logo and Rapid Router UI on Safari and tablets

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1339]
Logo is stretched and zoom doesn't work/fit

**Comment by lauracumming** [comment]
We also need to fit the cookie banner

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/1339?planning-poker) with Zenhub @faucomte97 @KamilPawel

**Comment by SKairinos** [comment]
still seems ![image.png](https://images.zenhubusercontent.com/63ed10d0c8cb61b145ebeb5c/51b43517-cffa-4fd4-a249-f7eeec52cd48)

**Comment by faucomte97** [comment]
The logo issue still is.
When it comes to the Rapid Router UI - this has been fixed, the zoom buttons now are entirely visible on all screen sizes.

**Comment by faucomte97** [comment]
Closing this as we agreed it doesn't affect enough devices for us to work on it for now. Might revisit later.
