### ISSUE TITLE
Better solution for Lv 43

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/rapid-router#1349]
Reported by a teacher+student, this seems a better solution for lv 43:

![rr43.png](https://images.zenhubusercontent.com/601ac69612e543a2f4f6072d/228a4923-1957-481f-b0ee-3586131a29f0)

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/1349?planning-poker) with Zenhub @SKairinos @faucomte97
