### ISSUE TITLE
Break down and add tasks to this epic

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1385]

**Comment by faucomte97** [comment]
Needed in portal:
	From rapid-router:
		Models: Episode, Level, Attempt
		Test functions: create_attempt, create_save_level
		Actual functions for level management
		URLs
	From aimmo:
		Models: Game
		Worksheet information
		The game creator function
		URLs

Needed in rapid-router:
	From portal:
		app_tags
		Test base_page for Selenium tests
		Other Selenium test pages
		URLs
	From aimmo:
		URLs

Needed in aimmo:
	From portal:
		The AddGameForm
		URLs
	From rapid-router:
		URLs

**Comment by faucomte97** [comment]
Needed in portal:
	From rapid-router:
		Models: Episode, Level, Attempt
		Test functions: create_attempt, create_save_level
		Actual functions for level management
		URLs
	From aimmo:
		Models: Game
		Worksheet information
		The game creator function
		URLs

Needed in rapid-router:
	From portal:
		app_tags
		Test base_page for Selenium tests
		Other Selenium test pages
		URLs
	From aimmo:
		URLs

Needed in aimmo:
	From portal:
		The AddGameForm
		URLs
	From rapid-router:
		URLs

**Comment by faucomte97** [comment]
Needed in portal:
	From rapid-router:
		Models: Episode, Level, Attempt
		Test functions: create_attempt, create_save_level
		Actual functions for level management
		URLs
	From aimmo:
		Models: Game
		Worksheet information
		The game creator function
		URLs

Needed in rapid-router:
	From portal:
		app_tags
		Test base_page for Selenium tests
		Other Selenium test pages
		URLs
	From aimmo:
		URLs

Needed in aimmo:
	From portal:
		The AddGameForm
		URLs
	From rapid-router:
		URLs
