### ISSUE TITLE
Coin image when completing an episode is missing

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1393]
**Describe the bug**
The image for the coin that shows up when an Episode is completed seems to be missing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a student.
2. Complete an Episode in Rapid Router.
3. Observe that the Episode coin is missing.

**Expected behaviour**
The coin should be visible.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/e465d4ae-e325-4c23-bbc2-5a4519de0ae5)If applicable, add screenshots to help explain your problem.

**Comment by sebp999** [comment]
![Screenshot 2023-03-04 at 11.14.04.png](https://images.zenhubusercontent.com/5dd165e72de56b0001c54603/d4a448ee-0954-4318-a072-59333e1e20d3)

**Comment by sebp999** [comment]
Made a PR: https://github.com/ocadotechnology/rapid-router/pull/1425

**Comment by SKairinos** [comment]
I have reviewed and approve of this PR. Waiting to ask some questions from @faucomte97 tomorrow morning about acceptance and review process. Will accept and merge after that.
