### ISSUE TITLE
Pop-up buttons

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1412]
Across different devices - need checking/adjusting
Also check pop-up window on tablets

The buttons need to be aligned to the buttons in the main RR popup (the rounded ones)

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/1412?planning-poker) with Zenhub @faucomte97 @SKairinos

**Comment by faucomte97** [comment]
Done
