### ISSUE TITLE
Exiting a level on Rapid Router doesn't take the user back to the level where they were

### ISSUE THREAD

**Issue by RadhikaGudipati** [ocadotechnology/rapid-router#1415]
## Task Description

Exiting a level on Rapid Router doesn't take the user back to the level where they were

## Acceptance Criteria
- [x] User is directed to the correct section when using the back or exit

### Analytics Requirements
- [ ] ...

### Copywrite Requirements
- [ ] ...

**Comment by lauracumming** [comment]
This worked for me

**Comment by lauracumming** [comment]
✅ Checked
