### ISSUE TITLE
Level editor doesn't remember level language choice when loading a level

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1436]
**Describe the bug**
When loading a custom level, the level editor doesn't seem to remember (or load) the value of the level language (Blockly, Blockly w/ Python view or Python). It seems to default to "Blockly" even if the level has previously been saved with another option. This can cause unwanted changes in the level if the creator goes back to edit it some more and doesn't notice the wrong default value.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a custom level in Rapid Router and select "Blockly with Python view" or "Python" language.
2. Save the level and then "Play" it to confirm the right language has been saved.
3. Go back to Create mode, and load in your new level.
4. In the "Code" tab, notice that the Language dropdown has "Blockly" selected as default instead of your previous choice.

**Expected behaviour**
When loading the level and going to the "Code" tab, the Language dropdown should have the previously saved value as the default value.

**Comment by sebp999** [comment]
Made a PR: https://github.com/ocadotechnology/rapid-router/pull/1491

**Comment by lauracumming** [comment]
Checked ✅
