### ISSUE TITLE
Add draggable scenery to Level Editor

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1457]
Users currently have to click on any scenery elements to add them to their level creation. 
We would like users to be able to drag the objects across to the canvas. 

The screen recording demonstrates that the users cannot currently drag the object and can only click on the object.

https://images.zenhubusercontent.com/18399425/ac56c190-fa77-4661-a910-57487337de85/non_draggable_demo.mov

https://www.codeforlife.education/rapidrouter/level_editor/#

**Comment by SKairinos** [comment]
I ran into this issue
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlUvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87198c4cdd8232f06b6d310e7a670ab868d45f1d/image.png" alt="image.png" />

**Comment by lauracumming** [comment]
LGTM - 
but the behaviour for the square bush is different  to the other bushes. Just wondered if that was accidental? It doesn't 'pop'[Uploading... Screenshot 2024-06-06 at 14.03.06.png]

**Comment by lauracumming** [comment]
Oh I see. It's quite nice. 
Maybe we just need to make the square bush a bit bigger then, but it can be a new task. This is fine.

**Comment by faucomte97** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM

**Comment by SKairinos** [comment]
LGTM
