### ISSUE TITLE
Run Pyodide in thread with timeout

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/rapid-router#1458]
We need to create a solution where user's code is executed in a thread, separate from the main thread. 

The understanding is that Pyodide executes the user's code on the main thread and sends the resulting action to the BE every 2 seconds. However, the concern is that if the user's code goes into an infinite loop, there is no way to stop executing there code and so no more actions will be sent to the BE.

Execute the user's code on a new thread with a timeout of 2 seconds. If the timeout is reached, send a WaitAction to the BE by default.

**Comment by cewei8483** [comment]
It seems to me that timeout is already handled (by function `timeoutIfWorkerTakesTooLong` in the file `game_frontend/src/redux/features/AvatarWorker/operators.js`)
There is also a test that tests infinite while loop - see `game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts`

**Comment by cewei8483** [comment]
Besides, I think Pyodide worker is initialized in another thread from this piece of code:

![image.png](https://images.zenhubusercontent.com/642aa7e9121daf640bf00067/94305782-a641-425d-b35a-c840ac0afb11)

**Comment by faucomte97** [comment]
Closing as we could not replicate the issue
