### ISSUE TITLE
Introducing 'else' in RR

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/rapid-router#1470]
## Task Description
else doesn't seem to have been explicitly introduced. Can it be in the text for L36 and then the exemplar solution changed?

**Comment by lauracumming** [comment]
@rdcruzCFL yes. Happy to do this. Do you have the copy?

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/1470?planning-poker) with Zenhub @faucomte97 @SKairinos

**Comment by lauracumming** [comment]
@rdcruzCFL

**Comment by rdcruzCFL** [comment]
Instead of: 
**You can change the If block to make more choices. Click on the star in the If block and add Else if.
This will tell the van what to do if the first If direction can't be done.
For example, tell the van to Turn left If the road exists left. Add Else if the road exists right, Turn right.
This uses fewer blocks and makes sure that only one step is taken in each loop.
This type of algorithm is called a 'general algorithm' as it can be used with most simple routes.**
Have this text:
**You can change the if block to make more choices. Click on the star in the if block and add else if.
This will tell the van what to do if the first if direction can't be done.
You can also add and else block to tell the van what to do if none of the conditions match
For example:
if there is a road ahead, go forwards
else if there is a road left, turn left
else, go right

This is a general algorithm, it can be used for lots of different routes!**

Can that code be a screenshot of the RR code instead?

**Comment by rdcruzCFL** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b7e76a5998ad972b1f9898c12acb94969ed9532/image.png)

**Comment by faucomte97** [comment]
@SKairinos Just realised we missed the last sentence of the intro text: This is a general algorithm, it can be used for lots of different routes!

We need to add it in.

**Comment by rdcruzCFL** [comment]
Please can we change the title on the pop-up window?  It is currently **What else? If-else, that's what!**
Can it be
**What else? If-else if-else, that's what!**

**Comment by lauracumming** [comment]
✅ Checked
