### ISSUE TITLE
Video sound keeps playing after closing the popup it's in

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1476]
**Describe the bug**
When the user plays a video in Rapid Router, whether or not logged in, and closes the pop-up without first stopping or pausing the video, the video continues to play and the user is left confused.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a Rapid Router level with a video (eg, [level 19](https://www.codeforlife.education/rapidrouter/19/#myModal))
2. Start the video in the popup
3. Close pop-up without stopping video
4. See the joy that happens 😬

**Expected behaviour**
It should stop playing with pop-up closure

**Screenshots**
![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/48523762-4705-49e0-adc0-621de4841903)

**Comment by AbdelrahmanDeghedy** [comment]
Created an MR with a possible fix: https://github.com/ocadotechnology/rapid-router/pull/1554

**Comment by lauracumming** [comment]
Looks good
