### ISSUE TITLE
Student login link in anonymous RR level creator is broken

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1477]
**Describe the bug**
When a anonymous (not logged in) user is using the Level Creator in RR, and tries to use functionality which requires them to be logged in (ie loading, saving or sharing a level), we show them a message prompting them to login.
That message has individual links to each login form (student, teacher or independent).
The link for the student login is broken and needs to be fixed - probably because it wasn't updated after we updated the student login process.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [Rapid Router level editor](https://www.codeforlife.education/rapidrouter/level_editor/#).
2. Click on Load, Save or Share.
3. Click on the "student" hyperlink.
4. Notice that the custom 404 error page shows.

**Expected behaviour**
The user should be redirected to [the student login page](https://www.codeforlife.education/login/student/).

**Screenshots**
Popup with the broken link:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTNmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1c7a639af5d22689a2a47ae58e5a72eb85afd67c/image.png)

**Comment by lauracumming** [comment]
Checked ✅
