### ISSUE TITLE
create new level links

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/rapid-router#1489]
[see design on figma](https://www.figma.com/file/cfTZqEi7gmrGylwCURz9EQ/design-system?type=design&node-id=0-1&mode=design&t=DRlQZO3z3bjiClEG-0)

add new links to the new levels in the list of all levels

**Comment by lauracumming** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd29kQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c006fd355c379b18b099a1c1b1d8dd9c51dfbe7e/Screenshot%202023-10-10%20at%2010.58.43.png)

**Comment by SKairinos** [comment]
@lauracumming, where can I find the titles for each level? [This doc](https://docs.google.com/document/d/14qjWrbvUX6qONgiYYBsW5KpjpfQR9liYudIuInmFZMU/edit) is missing most of them.

**Comment by SKairinos** [comment]
@lauracumming, where can I find the titles for each level? [This doc](https://docs.google.com/document/d/14qjWrbvUX6qONgiYYBsW5KpjpfQR9liYudIuInmFZMU/edit) is missing most of them.

**Comment by lauracumming** [comment]
https://www.figma.com/file/6802Amjc4GKRdqzm26ozaw/While-Loop-levels?type=design&node-id=1%3A396&mode=design&t=2rR96gzKIP2ax3HZ-1

**Comment by SKairinos** [comment]
@lauracumming, I think you missed the description for level 115
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0tCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5808f6c9056b2ec6871682766c474d93d8006ff5/image.png)

**Comment by SKairinos** [comment]
@lauracumming, do we have hints for these levels? Or is it the case we sometimes don't have a hint for a level?

**Comment by lauracumming** [comment]
@rdcruzCFL added hints to the doc. 
Let's check with her that 115 description isn't somewhere too as she was tasked to check these.
