### ISSUE TITLE
multiple blocks highlighting during play

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/rapid-router#1496]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d93eb0c4387f2dda359eb3383093f468ffa96b9e/Screencast%20from%2012-10-23%2012-08-15.webm)

sometimes RR goes into an invalid state where multiple blocks are highlighted simultaneously. unsure if this means multiple blocks are being executed.

**Comment by faucomte97** [comment]
Fixed.
