### ISSUE TITLE
question if level 39 "dead ends" is needed

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/rapid-router#1497]
since we want to take a longer route with a general algorithm instead of a case-specific algorithm, we should question whether this dead end level is needed.

**Comment by SKairinos** [comment]
since we want to take a longer route with a general algorithm instead of a case-specific algorithm, we should question whether this dead end level is needed.

**Comment by faucomte97** [comment]
Closing until it inevitably comes back.
