### ISSUE TITLE
Character drives over trees in level 36

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1503]
**Describe the bug**
In level 36, there are trees that are so close to the road, they cover some of it. When the character (either the Van, or the Sleigh in December) drives on the tiles under the trees, the asset image drives over the trees. Most likely because the character image is generated after the trees so the character's z-index is higher.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [level 36](https://www.codeforlife.education/rapidrouter/36/).
2. Add some blocks so the character gets to the tiles under the trees.
3. Press Play.
4. Notice that the character's image is "on top" of the trees when it should be under them.

**Expected behaviour**
The character image should be on top of the road, as it is now, but below the trees (or any other decor item that is "higher" than the road).

**Additional context / Acceptance criteria**
Two solutions are possible here:
- [ ] (hard solution): Fix the game rendering logic so that the van / sleigh is properly in between the road and the trees. This means, essentially, fixing the z-index values (eg: road.z_index = 0, van.z_index = 1, trees.z_index = 2). 
- [ ] (easy solution): Move the trees so they don't cover the road. The x and y values of the LevelDecor objects for level 36 would need to be changed.

Optional task:

- [ ] Perform a quick scan of the other levels to double-check if the same problem affects any other levels (only needed if doing the easy solution).

**Screenshots**
![Screenshot from 2023-12-11 15-18-44](https://github.com/ocadotechnology/rapid-router/assets/33633200/5fa042f8-1d30-428d-9649-fc60376f83c0)

- [x] laura

**Comment by lauracumming** [comment]
- [ ] Approved on staging

**Comment by lauracumming** [comment]
- [ ] Check Cookie banner: banner loads, categories in the right order, cookies disabled by default
- [ ] Check Rapid Router: game loads, can solve a level, can save a workspace, can create a level, can save a level, scores get saved, scoreboard loads
- [ ] Check OS on browserstack

**Comment by SKairinos** [comment]
This is not working for me on staging<img width="225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a715742ba8bbe5e5540812ded964dff777d46135/image.png" alt="image.png" />

**Comment by SKairinos** [comment]
- [x] Approved on staging

**Comment by lauracumming** [comment]
- [ ] Check Cookie banner: banner loads, categories in the right order, cookies disabled by default

 

- [ ] Check Rapid Router: game loads, can solve a level, can save a workspace, can create a level, can save a level, scores get saved, scoreboard loads
- [ ] Check OS on browserstack
- [ ] Approved on prod

**Comment by lauracumming** [comment]
Browserstack seems to be in German for me?

**Comment by lauracumming** [comment]
Ready for checker 2

**Comment by faucomte97** [comment]
Looks good to me
