### ISSUE TITLE
Remove Dee from level 116 popup

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1518]
**Describe the bug**
A while back we updated the look and feel of the Rapid Router levels & episodes by making the Python levels (level 80 and above) more grown-up. This included a change in colour scheme and removing the Dee image from the intro popups in the levels.
We recently added levels 110-122 and level 116's intro popup has the Dee image in it. This is because it is the only level above level 80 which is a Blockly-only level.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [level 116](https://www.codeforlife.education/rapidrouter/116/#myModal).
2. Notice that Dee is in the intro popup.

**Expected behaviour**
Dee should not be in the popup.
As of now, I imagine the logic works as follows: if the level is a Blockly level => show Dee, otherwise (if level is Blockly w/ Python or just Python) => hide Dee.
The logic should then probably be amended so that any level above level 80 hides Dee in their intro popup.

**Screenshots**
![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/09d7150f-fbaa-4c28-a972-b47bee3735bd)

**Comment by AbdelrahmanDeghedy** [comment]
Do levels above 80 should hide all characters or just Dee? So is changing the logic to hide characters above level 80 correct?

**Comment by faucomte97** [comment]
Hi @AbdelrahmanDeghedy, at the moment yes, all levels above 80 should hide all characters. Changing the logic to hide all characters above level 80 should work fine 🙂
