### ISSUE TITLE
Level Editor layout is wonky

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1543]
**Describe the bug**
The Level Editor layout has become wonky. The grid has grown in size so it no longer fits in the window and the bin has moved closer to the centre of the window.
Additionally, when moving scenery assets onto the grid, the mouse cursor isn't in line with the grid and where the asset actually ends up - most likely a byproduct of the grid being oversized.

This is a side-effect of #1516. Reverting the code to what it was before that change "fixes" it, although the original issue comes back whereby the grid is cut off. A solution needs to be found to fix both problems.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [level editor](https://www.codeforlife.education/rapidrouter/level_editor/#).
2. Notice that the grid no longer fits in the window and the bin isn't in the bottom-right corner anymore.
3. Click on the "Scenery" tab on the side.
4. Click on any scenery asset.
5. Drag the asset from the corner of the grid to any point of the grid and notice that where your cursor is doesn't match where the asset ends up.

**Expected behaviour**
The grid should fit within the window and the bin should go back to the bottom-right of the window.
Assets that are added to the map should be in line with where the cursor is.

**Screenshots**
![Screenshot from 2023-11-28 13-59-37](https://github.com/ocadotechnology/rapid-router/assets/33633200/cfb1d8c3-6910-445c-a985-f2e00b4077f5)

**Desktop (please complete the following information):**
Probably all (double-check)

**Comment by SKairinos** [comment]
Can't drag objects into bin when bin is below grid
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlBhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ba6105f8f3e76860e2e42abcf59ead5f3bb25c2/Screencast%20from%2014-05-24%2011-03-48.webm)

**Comment by SKairinos** [comment]
I propose the following fix, we should be able to drag elements off the grid and release it into the bin. However, if the element is released off the grid and it's not over the bin, the element should be placed at _max x_ if it's x coordinate is over the max and _max y_ if it's y coordinate is over the max

**Comment by lauracumming** [comment]
- [ ] production approved

**Comment by lauracumming** [comment]
- [ ] Check Cookie banner: banner loads, categories in the right order, cookies disabled by default
- [ ]  Check Rapid Router: game loads, can solve a level, can save a workspace, can create a level, can save a level, scores get saved, scoreboard loads
- [ ]  Check OS on browserstack
