### ISSUE TITLE
Rename level 36

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1558]
## Task Description
[Level 36](https://www.codeforlife.education/rapidrouter/36/#myModal) is currently titled "**What else? If-else, that's what!**".
We've recently updated the solution and description of this level, and Rebecca would like us to rename it to "**What else? If-else if-else, that's what!**"

![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/809cc2e6-3fa4-4416-b45b-307f92d20ea7)

## Acceptance Criteria
- [ ] Update the title of level 36 to **What else? If-else if-else, that's what!**.
- [ ] Also update the title in the Gitbook resources (ask the team for edit access).

**Comment by juandesenvolvedor** [comment]
Could you please assign me for this issue?
