### ISSUE TITLE
Level 14 solution spawns an extra block

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1572]
**Describe the bug**
Solving level 14 as a teacher loads the correct solution but there is an extra block (unattached to the rest of the program) which is loaded in. It doesn't need to be there, and it can lead to confusion.

**To Reproduce**
Steps to reproduce the behaviour:
1. [Login as a teacher](https://www.codeforlife.education/login/teacher/).
2. Go to [level 14](https://www.codeforlife.education/rapidrouter/14/).
3. Press the "Solve" button.
4. Notice that there is an extra rogue block on the left-hand side (behind the overlay).

**Expected behaviour**
The extra block should not be loaded in.

**Screenshots**
![Screenshot from 2024-01-18 17-20-30](https://github.com/ocadotechnology/rapid-router/assets/33633200/4ac3a21a-fa81-4144-85f9-1742f22fa1e4)

**Additional context**
This is a probably due to a mistake in the actual XML solution code for level 14.

**Comment by akurtle** [comment]
Hello, I would love to work on this one!

**Comment by akurtle** [comment]
Hello, I would love to work on this issue!
I have done a pr on the codeforlife-workspace to be added to the contributers

**Comment by faucomte97** [comment]
Hi @akurtle, awesome news!
I just left a comment on your PR in the codeforlife-workspace repo 😃

**Comment by faucomte97** [comment]
Congratulations @akurtle, you are now an official Code for Life contributor!
If you haven't already, feel free to start working on this issue and raise a PR whenever you want us to review your work 😄

**Comment by akurtle** [comment]
Hello! I fixed the XML code (there was an extra block) but I was unable to test it as I wasn't able to look at level 14 from a teacher's perspective through localhost, please let me know how I can do that. Thanks!

**Comment by faucomte97** [comment]
Hi @akurtle, great news!

When you are running the project on localhost, you can create a teacher account by filling in the register form. You can use any email address, it doesn't need to be real as it's all local. Any email content you need (mainly for the email verification) is printed to your terminal, so you can follow the verification links there. It's a pretty handy process if you want to have multiple test accounts for different scenarios. Once you've made a test account like that you can just use them to login as a teacher, or any other user type.

Otherwise, you can use one of our preexisting test accounts which are created by the migrations 🙂

**Comment by akurtle** [comment]
Thank you so much! I got it to work. I have opened a PR.

**Comment by faucomte97** [comment]
@akurtle I've just merged in your PR 😄 
It's deploying now to our staging server where we will manually test it again before we release it to our production site.
Once we've deployed it to our production site we'll keep this task open for 1 more day or so we can perform some final manual checks and if all is good we will close this task as done!
