### ISSUE TITLE
Saving feature is broken

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1573]
**Describe the bug**
The saving feature in the Rapid Router levels is broken. Users can no longer save a workspace (program) for later use. This is quite disruptive as it seems to be a highly used feature.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as any user.
2. Go to any Rapid Router level.
3. Make a program by attaching any blocks to the Start block.
4. Open the "Save" tab, enter a name for your workspace and click "Save".
5. Notice that you get an error message and the saving fails.

**Expected behaviour**
The workspace should successfully be saved and added to the lists of workspaces that you can then load using the Load tab.

**Screenshots**
![Screenshot from 2024-01-18 17-25-10](https://github.com/ocadotechnology/rapid-router/assets/33633200/3cafb7e7-a079-4953-a94c-2a443da366d8)

**Additional context**
There are a few errors that could be a good place to start understanding why this is happening:
- the two errors in the browser dev tools when submitting the Save request
- [this error in GCP error reporting](https://console.cloud.google.com/errors/detail/CKWk9v63x5eikgE;time=P1D?project=decent-digit-629) (only accessibly to internal employees added to the GCP project).

Analysis of the Python exception stack trace seems to indicate that this bug might have been introduce by [this commit](https://github.com/ocadotechnology/rapid-router/commit/cad596b26de2f93940e1836ae9c10450d6c4b2de).

**Comment by AbdelrahmanDeghedy** [comment]
I want the credentials that allow me to login inside the dev server

**Comment by lauracumming** [comment]
Looks good
