### ISSUE TITLE
Using translations with Blockly

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1597]
**Describe the bug**
We have tried to implement other languages from [Crowdin](https://crowdin.com/project/code-for-life) to Blockly, but it breaks Rapid Router when special characters are in a language.

This needs investigation so that we can use the translations.

https://developers.google.com/blockly/guides/configure/web/translations

**Additional context**
We would like to test this with Catalan translation first.

**Comment by faucomte97** [comment]
@evemartin

**Comment by lauracumming** [comment]
duplicate
