### ISSUE TITLE
Translate custom blocks in Rapid Router

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/rapid-router#1612]
In order to get the block translations working properly, we need to move the translated labels for the custom blocks into the Rapid Router language files (in blockly/msg/js) and reference them properly when the custom blocks are set up. 

An example of how to format the translated labels can be found at the bottom of the `fr.js` language file - the `MOVE_FORWARDS_TITLE` and `MOVE_FORWARD_TOOLTIP` messages are custom and are used for the `move_forwards` custom block. 

- [ ] Move translated labels for custom blocks from CrowdIn to Rapid Router's language files
- [ ] Add Blockly.Msg label references to the custom block definitions (instead of hardcoded strings)

**Comment by SKairinos** [comment]
@evemartin, I converted this to a GH issue

**Comment by evemartin** [comment]
Thank you!! I have linked it to the PR

**Comment by lauracumming** [comment]
- [ ] staging approved

**Comment by faucomte97** [comment]
Same

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
