### ISSUE TITLE
Save user's preferred language across Rapid Router levels

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1615]
At the moment, whenever you leave a level and select a new one, the language dropdown resets (to your browser's default language) even if you have changed it in the level. It would be good if Rapid Router saved the user's preferred language across levels instead of resetting it every time. 

One possible direction to look in for this ticket is cookies, similar to what we did with the Rapid Router mute cookie a little while ago.

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/rapid-router/1615?planning-poker) with Zenhub @evemartin @faucomte97 @SKairinos

**Comment by evemartin** [comment]
Update before I go on holiday: tested on dev and ready for review!

**Comment by faucomte97** [comment]
Reviewing - checking something with the legal team re cookie consent behaviour.

**Comment by faucomte97** [comment]
Ready for review on staging.
Please test that the cookies not only work when consent to functional cookies, but also that the cookies get deleted when withdrawing consent after the cookies have been activated.
You can check that in the Application tab of the browser DevTools when looking at the cookie list. The `muted` and `preferredLanguage` cookies should both disappear (only when going back to a Rapid Router level, not before).

**Comment by SKairinos** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by SalmanAsh** [comment]
LGTM
