### ISSUE TITLE
Cow placement

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1617]
**Describe the bug**
It is possible to place a cow at the start and end of a map. 
This shouldn't be possible. No objects should be allowed on these squares.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Level Creator and create a map'
2. Click a cow
3. Drag to start square
4. See cow is happy on square

**Expected behaviour**
Cow should not be happy on square, cow needs to be forbidden from square

**Screenshots**
<img width="476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3puQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eda4cf1f0eb7918ab88a840e21bdebce6133edfb/Screenshot%202024-05-16%20at%2012.44.55.png" alt="Screenshot 2024-05-16 at 12.44.55.png" />

**Additional context**
Please stop this cow behaviour

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/rapid-router/1617?planning-poker) with Zenhub @faucomte97 @SKairinos @evemartin

**Comment by faucomte97** [comment]
Reviewed and left comments. Mentioned a user feedback concern that @lauracumming might have some input on.

Depending on what is decided, feel free to ping me even if I'm offline and I can rereview.

**Comment by evemartin** [comment]
@faucomte97 I've responded to your comments! Laura suggested we leave the user feedback as it is (with the highlighted red/green squares) for right now but discuss adding more in the future - I have created [this task ](https://app.zenhub.com/workspaces/code-for-life-design--research-5db8789ca7e95f00017a07df/issues/gh/ocadotechnology/codeforlife-design/431)to cover it!

**Comment by SKairinos** [comment]
I ran into this issue
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlkvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55791bbd15167758d0ab8d675eb34249875a5f10/image.png" alt="image.png" />

**Comment by evemartin** [comment]
When exactly did this screen appear?

**Comment by lauracumming** [comment]
Are you still logged into the admin?

**Comment by SKairinos** [comment]
maybe. why would that have an impact on RR, though? is it a known bug?

**Comment by SKairinos** [comment]
Maybe, will check. Why would that impact RR, though? Is it a known bug?

**Comment by faucomte97** [comment]
LGTM. Stefan's issue is unrelated: https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/codeforlife-portal/2315

**Comment by faucomte97** [comment]
LGTM

**Comment by SKairinos** [comment]
LGTM
