### ISSUE TITLE
Bug - custom level score should be 10/10

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1619]
**Describe the bug**
It says 10/20, rather than 10/10 when the scoring comes up on level editor

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Level editor'
2. Click on 'play a level that you created previously or make a new one'
3. complete the level

**Expected behaviour**
Should be 10/10 innit

**Screenshots**
<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1QzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57f7f283efd3b7403dd7e4f41d11e6f379f56825/Screenshot%202024-05-08%20at%2011.52.49.png" alt="Screenshot 2024-05-08 at 11.52.49.png" />

**Additional context**
@faucomte97  knows what needs changing

### Staging Approved
- [x] Checker 1
- [x] Laura

### Prod Approved
- [x] Checker 1
- [ ] Laura

**Comment by faucomte97** [comment]
Messaged @evemartin about the issue that was found on dev.

Other than said issue which I believe is a bug unrelated to this task, everything on dev looked good to me. I have approved so can be merged.

**Comment by lauracumming** [comment]
LGTM

**Comment by SKairinos** [comment]
I ran into this issue
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlEvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d86e87f0f583c3ec9c3659cbf4711806437f94d/image.png" alt="image.png" />

**Comment by faucomte97** [comment]
LGTM

**Comment by faucomte97** [comment]
Stefan's issue is unrelated: https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/codeforlife-portal/2315

**Comment by faucomte97** [comment]
LGTM
