### ISSUE TITLE
Translated blocks are missing 'do'

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1620]
## Task Description
We are missing 'do' as we removed the request for this in the translations.

## Acceptance Criteria
- [ ] add back into translations requests
- [ ] get translated

### Analytics Requirements
- [ ] Add tracking to dropdown to see how much it is clicked

### Copywrite Requirements
- [ ] As required

### Staging approved
- [x] Checker 1
- [x] Laura 

### production approved
- [x] Checker 1
- [x] Laura

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
