### ISSUE TITLE
missing buttons on overwriting modal

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1626]
When a user is saving a created level in the Level Editor, they can choose to overwrite an old level with a new level. When the user attempts to do this, a modal appears asking them to confirm that they'd like to overwrite the old level. This modal has no confirmation button.

Steps to reproduce the bug:
1. Go to the Level Editor and create and save a random level as per normal
2. Go back to the Level Editor and create a new level
3. When done creating the level, go to the "Save" tab and click on the existing level you created in Step 1
4. Click Save
5. The following modal will appear:

<img width="1601" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a71541869e05a76df444bf02e82a9d341ab7d319/image.png" alt="image.png" />

**Comment by evemartin** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by EnoraHauduc** [comment]
LGTM
