### ISSUE TITLE
Add draggable scenery to Level Editor (traffic lights and cows)

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1635]
This task is a continuation of [task #1457](https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/rapid-router/1457). The remaining part of the task is to make traffic lights and cows draggable in addition to decor elements.

**Comment by lauracumming** [comment]
The cows and traffic lights don't drag for me

**Comment by evemartin** [comment]
I'm not sure why but it looks like my changes might not have been on staging after all - I've started a manual deployment now so hopefully this should be testable after that finishes. Sorry about that!!

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
