### ISSUE TITLE
Rapid Router - electric graphics for level editor 

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1636]
## Task Description
We would like to make RR greener. 
This is the first step by adding elements to the level editor. 

## Acceptance Criteria
- [ ] - add solar panels to scenery (farm, grass)

### Analytics Requirements
- [ ] None

### Copywrite Requirements
- [ ] Add alt text to explain what the image is

**Comment by evemartin** [comment]
I wasn't completely clear on what to do if the user places a solar panel and then changes the theme or what to display for a solar panel using the Christmas theme - what I've gone with for now is that whenever the theme changes to one without solar panels (i.e. snow or city) the level will display a different piece of scenery that's the same size as a solar panel (i.e. tree1 for snow and school for city). Let me know if something different would be better though and I can change it!

**Comment by lauracumming** [comment]
Sounds like a good call. We can add a snow ticket to the backlog for design if we haven't already.

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
