### ISSUE TITLE
invalid cow squares remain highlighted

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1643]
**Describe the bug**
Sometimes after a cow is placed on an invalid square, the square remains highlighted when the user moves their mouse away.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level Editor
2. Add a cow to the grid and drag it to be right on the leftmost edge of an invalid square (see screenshot)
3. Drop the cow in that position and move your mouse away to the left, i.e. do not move your mouse over the square
4. Notice that the square stays highlighted white when it should not be highlighted at all
5. Bonus: when you move your mouse over and off the highlighted square, only then does it unhighlight

**Expected behaviour**
The cow square should unhighlight as soon as the cow is dropped

**Screenshots**
![Screenshot from 2024-06-06 14-21-44](https://github.com/user-attachments/assets/eb961d2a-2081-4525-8747-854e577574d4)

**Comment by RaihanRasheedApurbo** [comment]
FYI: I am working on a fix on this.

**Comment by SKairinos** [comment]
@RaihanRasheedApurbo , we're not sure if you're still active on this we'll change the status of this task to "To Do". If you're still working on this, please comment and we'll put it back in "In Progress".
Thank you for all your contributions! 🎉

**Comment by RaihanRasheedApurbo** [comment]
@SKairinos @faucomte97 https://github.com/ocadotechnology/rapid-router/pull/1752

**Comment by SKairinos** [comment]
Ty Raihan. I have re-assigned you to this ticket and attached your PR to this ticket. We'll review this and get back to you.

**Comment by lauracumming** [comment]
I think this is okay - not sure what has changed.
There is still a bit of a delay sometimes but once save it's okay.

<img width="332" alt="Image" src="https://github.com/user-attachments/assets/d4e8b23b-b05a-443b-b078-54d674edf3df" />
<img width="667" alt="Image" src="https://github.com/user-attachments/assets/f0dfd66d-5529-40f1-9d3b-014b40388b29" />
<img width="920" alt="Image" src="https://github.com/user-attachments/assets/df6427e7-46fb-4ede-adcb-383cdb825600" />
