### ISSUE TITLE
Animating gauge for electric van vehicle

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1651]
## Task Description
 We would like to animate the electric charge graphic in accordance to the way we use the petrol graphic

## Acceptance Criteria
- [ ] Full range of movement that decreases with movement of electric van

### Analytics Requirements
- [ ] None

### Copywrite Requirements
- [ ] None
 [Uploading... Electric_gauge.svg]

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
