### ISSUE TITLE
Add electric gauge to van

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1652]
## Task Description
Add electric gauge to van theme

## Acceptance Criteria
- [ ] Gauge to appear when electric van is selected - for relevant levels.

### Analytics Requirements
- [ ] None

### Copywrite Requirements
- [ ] None

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM

**Comment by evemartin** [comment]
Update before I go on holiday: needs to be checked on prod

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
