### ISSUE TITLE
Add electric van sound

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1654]
We would like to add [this fan sound](https://pixabay.com/sound-effects/electric-desk-fan-turning-on-and-off-121339/) to Rapid Router for the electric van startup.

- [ ] electric van sound added

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/rapid-router/1654?planning-poker) with Zenhub @evemartin @faucomte97 @SKairinos

**Comment by faucomte97** [comment]
LGTM

**Comment by evemartin** [comment]
Update before I go on holiday: needs to be checked on prod

**Comment by lauracumming** [comment]
LGTM - could be a little shorter, but fine for now

**Comment by faucomte97** [comment]
LGTM
