### ISSUE TITLE
Level editor: can't save text fields with certain emojis

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1661]
**Describe the bug**
An error occurs when trying to save a level with certain emojis in the text fields (hint, description, subtitle)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Rapid Router Level Editor and create a new level - in the hint, description, and subtitle boxes, add this emoji: https://emojipedia.org/smiling-face-with-heart-eyes
2. Click Save
3. An error will appear

**Expected behaviour**
The level should save with the emojis 

**Additional context**
- the emoji linked doesn't work, but some emojis do work, like the [red heart](https://emojipedia.org/red-heart)
- this probably has to do with the way the emojis are encoded in the database - [link to the error on GCP](https://console.cloud.google.com/errors/detail/CJH_3ZfvnvvCFA;service=default;version=169;time=P1D?project=decent-digit-629), [link to Django docs on unicode](https://docs.djangoproject.com/en/3.2/ref/unicode/#models), [link to StackOverflow suggested solution](https://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django)

**Comment by faucomte97** [comment]
No longer relevant - the switch to PostgreSQL now allows for emoji characters.
