### ISSUE TITLE
Outdated link to Blockly guide

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1663]
**Describe the bug**
The link to "read more about Blockly" is broken and needs updating.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [the Rapid Router landing page](https://www.codeforlife.education/rapidrouter/).
2. Click on the link in "You can read more about Blockly here".
3. Notice that the Gitbook page says the content was not found.

**Expected behaviour**
The link should redirect the user to the correct page in Gitbook.
Ask a member of the CfL team for the exact link.

**Screenshots**
![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/d88fa917-593b-4348-8bf0-76c4ad55bd63)

**Comment by SKairinos** [comment]
LGTM

@lauracumming, this is correctly in the RR space as these are RR specific blocks.
