### ISSUE TITLE
Allow for cows to be placed on a non-road square

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1672]
## Task Description
The level editor lets you place cows in the map. Currently, cows can only be placed on **valid road squares**, ie a road square that isn't a start or house square.
The user should also be able to place cows on any other square, for scenery purposes.

![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/1112624e-2443-488f-b3b9-143e8e880ac7)

In this example, the cow on the road has been successfully placed whereas the cow in the "field" has not been registered as "placed" by the level creator.

## Acceptance Criteria
- [ ] Allow for cows to be placed on non road squares

**Comment by RaihanRasheedApurbo** [comment]
HI @faucomte97 can you assign me to this ticket? The description is quite clear.... can you help me pointing to similar MR or the files that I might start looking at to solve this issue.

**Comment by faucomte97** [comment]
@RaihanRasheedApurbo This PR should be helpful 🙂 https://github.com/ocadotechnology/rapid-router/pull/1625

**Comment by lauracumming** [comment]
LGTM (PROD)

**Comment by faucomte97** [comment]
LGTM
