### ISSUE TITLE
Python Den game page

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1676]
## Task Description
We would like to create a game page that hosts the new Python Den levels and the Raspberry Pi IDE. 

## Acceptance Criteria
- [ ] Follow designs for the look and feel

### Analytics Requirements
- [ ] Views
- [ ] Attempts

### Copywrite Requirements
- [ ] TBC

**Comment by evemartin** [comment]
Screenshots of the Python Den game pages:
<img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92d4a0a54b23ce2c158d82874e4cd8b09aff5bc8/image.png" alt="image.png" />
<img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3c83f18045368632f773dc2f28263ee609d31cb/image.png" alt="image.png" />
@lauracumming do you have a preference of color for the IDE's "Run" button, and do you have a preference for what the initial starting code is in the `main.py` half of the IDE?

**Comment by evemartin** [comment]
Handover notes: all that remains to be done for this task is what's been brought up in the PR comments!

**Comment by faucomte97** [comment]
@lauracumming Since we are not embedding the IDE at the mo, can we have an updated version of the Python Den header **without** the Exit button please. Even if we were still embedding the IDE, the button should be a programmatically added overlay on top of the image instead of being in the image (for responsiveness purposes).

**Comment by faucomte97** [comment]
@lauracumming Just noticed it's an SVG so I can do it myself

**Comment by lauracumming** [comment]
You can export as you wish from Figma

**Comment by lauracumming** [comment]
LGTM (apart from 'next level')

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM
