### ISSUE TITLE
Text in top left corner of side bar in game isn't the right colour

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1679]
**Describe the bug**
The side bar in the game has two sections in the top-left corner with text written in black. They are the heading indicating whether the level is Blockly or Python, and the language dropdown.
While the text being black is OK for levels 1-109, it is not accessible in levels 110 onwards, since the background is grey.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 110.
2. Notice that the black text in the top-left corner is not accessible.

**Expected behaviour**
The text should be white so it can be easily legible - the change can be done across all levels.

**Screenshots**
![image](https://github.com/user-attachments/assets/0dd40ccc-83af-4683-ab0b-341dce006665)

**Comment by morganclarkeee** [comment]
Working on this task! :)

**Comment by evemartin** [comment]
Since the release of Python Den is coming up, I've picked this task up and made a PR for it here: https://github.com/ocadotechnology/rapid-router/pull/1708

**Comment by lauracumming** [comment]
Is this also related?

![Image](https://github.com/user-attachments/assets/5051a87d-60b4-46ea-b539-3c4e988f53d5)

on the level editor

**Comment by lauracumming** [comment]
Looks good apart from the jigsaw piece. I don't mind creating a separate task for this though so we can get this deployed.

**Comment by lauracumming** [comment]
LGTM
