### ISSUE TITLE
Overwriting levels

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1686]
**Describe the bug**
When you try to save over a level it gives you a warning, but no action option.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'level editor'
2. Create a level
3. Click on 'save'
3.Try to save with same name as previous level

**Expected behaviour**
Should have a button to edit or save

**Screenshots**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f8928340f98eebc8e0842bfe59090e534e60076/Screenshot%202024-07-28%20at%2019.23.49.png" alt="Screenshot 2024-07-28 at 19.23.49.png" />

**Comment by evemartin** [comment]
LGTM

**Comment by EnoraHauduc** [comment]
LGTM also
