### ISSUE TITLE
Cows crossing

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1687]
**Describe the bug**
Python levels with Cows throws error

**Screenshots**
<img width="946" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1134461d3c5a54f5417daaee0277610574754fc4/Screenshot%202024-07-28%20at%2019.24.51.png" alt="Screenshot 2024-07-28 at 19.24.51.png" />

**Comment by evemartin** [comment]
LGTM

**Comment by lauracumming** [comment]
When testing - I noticed that the Python commands were generic for my created level. Is it possible to apply the same rule to created levels too for the Python commands?

**Comment by lauracumming** [comment]
and this: is this the most user friendly we can be?<img width="208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWttQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f5b9fb07bf146723c198248ce0adeb11002d316/Screenshot%202024-08-01%20at%2013.21.00.png" alt="Screenshot 2024-08-01 at 13.21.00.png" />

**Comment by lauracumming** [comment]
my van is an animal

**Comment by faucomte97** [comment]
ah I see, yeah the issue is that the check for animal crossing shouldn't be part of the van object. But that's all we've got for now

**Comment by lauracumming** [comment]
LGTM

**Comment by EnoraHauduc** [comment]
LGTM

**Comment by lauracumming** [comment]
I'm not able to save in level editor. Can someone else check?<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c15ce621fa38d6a704796067549059e98f55a901/Screenshot%202024-08-02%20at%2015.53.03.png" alt="Screenshot 2024-08-02 at 15.53.03.png" />

**Comment by evemartin** [comment]
It seems to work okay for me - we do have a bug task that might relate to this, does it look relevant? https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/rapid-router/1627

**Comment by lauracumming** [comment]
Yep. That was it. LGTM
