### ISSUE TITLE
Broken link to Python commands doc

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1691]
**Describe the bug**
The "Help" popup in the Python levels has a broken link to our Python commands docs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 92.
2. Click "Help".
3. Click "the full list of commands".
4. Notice that the link leads to a broken page on Gitbook.

**Expected behaviour**
The link should redirect to the right page.
This is the correct link: https://code-for-life.gitbook.io/rapid-router/rapid-router-python-commands

**Screenshots**
![Screenshot from 2024-07-31 10-49-16](https://github.com/user-attachments/assets/8be01fba-945b-46da-955a-aef8ff74540e)

**Comment by lauracumming** [comment]
Not sure where to find the link to test

**Comment by evemartin** [comment]
There's one of these links in the hint for Python Den level 42!

**Comment by lauracumming** [comment]
LGTM

Although shouldn't all of this just be in the student section? Is it accessible for users that aren't logged in?

**Comment by SKairinos** [comment]
Some redundancy in the title + routing.

https://code-for-life.gitbook.io/rapid-router/rapid-router-python-commands

Could just be simplified to

https://code-for-life.gitbook.io/rapid-router/python-commands
