### ISSUE TITLE
Van goes flying and explodes if it does anything in front of a cow

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1692]
**Describe the bug**
For some reason, if the van (or any other character) executes an action block or action command in front of a cow, the van goes flying to the top-left corner of the map and explodes, and a popup shows up saying you've crashed into a cow.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as any type of user.
2. Go to the level editor.
3. Create a custom level with a cow on the road. It can be either a Blockly level or a Python level. If making a Blockly level, make sure you enable the "wait" block and the "increment" block.
4. Save the level and start playing it.
5. Write a program that gets the character to the square just before the cow and then runs the wait or increment command.
6. Observe that the character goes flying to the top-left corner and the game thinks it has crashed into the cow.

**Expected behaviour**
All characters should be able to run actions in front of a cow, just like they can on any other square.

**Screenshots**
![wait_cow_boom](https://github.com/user-attachments/assets/05243401-1cbc-4885-a334-ba4939e00c4f)

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM
