### ISSUE TITLE
Remove superfluous Python commands in Rapid Router - Level editor

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1693]
We need to create this rule in the level editor so that levels created only display relevant Python commands.

**Comment by faucomte97** [comment]
@lauracumming We might need a design for this first

**Comment by Ridwanah** [comment]
Hi, I want to work on this but I need some more direction. Do you want users to be able to specify the necessary Python commands in the level editor?

**Comment by faucomte97** [comment]
Hi @Ridwanah, yes that is the idea - @lauracumming we probably need a design for this task first?

**Comment by faucomte97** [comment]
Hi @Ridwanah, I'm really sorry for only getting back to you now.

After a discussion with the team, we've actually come to the conclusion that this task is not really feasible, or at least not enough for us to want to prioritise it right now. Apologies for this, we should've realised this sooner.
We will probably go ahead and close this task, are you OK to pick another one up instead?

**Comment by Ridwanah** [comment]
Hi, 
No worries. Thanks for telling me. I will pick up another task instead.

**Comment by faucomte97** [comment]
Thanks for understanding 🙏🏻
