### ISSUE TITLE
Implement pigeon in city

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1698]
## Acceptance Criteria
- [ ] ...
- [ ] ...

### Analytics Requirements
- [ ] ...

### Copywrite Requirements
- [ ] ...

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/rapid-router/1698?planning-poker) with Zenhub @evemartin @faucomte97 @SKairinos

**Comment by faucomte97** [comment]
Duplicate of #1674
