### ISSUE TITLE
Cleanup for Python Den release

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1705]
There are a few remaining steps that must be done just before the release of Python Den. This task is to address them:

- [x] mark Rapid Router Level 79 as a final level
- [x] set the `next_level` value of Rapid Router Level 122/Python Den Level 13 and unmark it as a final level
- [ ] delete old Rapid Router episodes 10 and 11, old Rapid Router levels 80-109, and all associated `LevelBlock` and `LevelDecor` objects
- [x] update tests to reflect these changes

**Comment by lauracumming** [comment]
LGTM
