### ISSUE TITLE
bug: cow reorients when dragged a second time

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1718]
**Describe the bug**
Right after a cow is dragged onto the Level Editor grid, when it is re-dragged to a new spot on the grid, its orientation changes. This reorientation does not happen if it has already been re-dragged to a new spot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Level Editor
2. Drag a cow to place it on the grid. Do not place it on a road
3. Re-drag the cow to a new spot on the grid. Notice that its orientation changes so that it faces a different direction

**Expected behaviour**
The cow's orientation while dragging should not change. (The orientation should only change when the cow is dragged to a road and the cow reorients to match the road, this functionality is working though so is not part of this task)

**Screenshots**

https://github.com/user-attachments/assets/0b2ba4bf-3733-4e47-bc52-df4e5e206bfe

**Additional context**
This task might be related to Task #1717 but because it is a behaviour specific to cows rather than all scenery I have made it separate just in case

**Comment by evemartin** [comment]
Video: 
[Screencast from 04-09-24 11:09:45.webm](https://github.com/user-attachments/assets/989a72a0-195a-47a8-aa1c-154814cb8719)

**Comment by faucomte97** [comment]
I don't believe this is relevant anymore, following the work on #1746. The remainder of the work is to make the cow rotatable, as covered in task #1717.
