### ISSUE TITLE
Add reviewed translations to Rapid Router

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1732]
## Task Description
Add newly verified translations for the Blockly blocks to the game and enable them in the language dropdown.

![image](https://github.com/user-attachments/assets/0e240e1f-6e01-4a2b-9146-bf6bdf4d4889)

## Acceptance Criteria
- [x] Polish (priority)
- [x] Brazilian Portuguese
- [ ] Italian
- [ ] Punjabi
- [ ] Urdu
- [x] Russian
- [x] Bulgarian (priority)

## Good Places to Start
Directory for the language files: https://github.com/ocadotechnology/rapid-router/tree/master/game/static/game/js/blockly/msg/js

Example PR which added a new block translation to certain languages: https://github.com/ocadotechnology/rapid-router/pull/1712

### Analytics Requirements
- [ ] Track usage of language buttons

### Copywrite Requirements
- [ ] See [doc](https://docs.google.com/document/d/1hXE7yKPf7_r_OTijbFZxnHKpohn_XvwLH8kBYhCvPoQ/edit?usp=sharing)

**Comment by henamistry-ot** [comment]
hello

**Comment by SKairinos** [comment]
Seems that we cannot do Punjabi as it's not one of Blockly's default translated languages. At least for our version of Blockly

**Comment by SKairinos** [comment]
italian, no. 17, is missing "do"
![Image](https://github.com/user-attachments/assets/485e9ecf-be91-48de-b31d-b214d3a10b87)

**Comment by faucomte97** [comment]
@SKairinos Can you double check with Marco (who did the translations) that the order of words for 19. and 20. matches the order in English - ie, the variable name *needs* to be put in the first input, and the value in the second input. Some languages, especially Romance languages, tend to invert the order of those words in the "obvious" translation so it might have to be tweaked.

**Comment by SKairinos** [comment]
Can do but ideally we should be doing this.
https://developers.google.com/blockly/guides/create-custom-blocks/localize-blocks#json_message_interpolation

**Comment by SKairinos** [comment]
Cannot do Urdu as format of strings is not consistent
![Image](https://github.com/user-attachments/assets/4500aa08-804a-44c8-8f06-c9e21001c4c1)

**Comment by SKairinos** [comment]
@faucomte97, I need marco's email

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM (prod)

**Comment by lauracumming** [comment]
LGTM
