### ISSUE TITLE
Hide RR Python levels

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1733]
## Task Description
We would like to remove the Python Levels from rapid Router.

## Acceptance Criteria
- [ ] Remove levels from RR levels page
- [ ] Check for any edge cases

### Analytics Requirements
- [ ] None

### Copywrite Requirements
- [ ] None

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
