### ISSUE TITLE
Moderation bug

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1742]
**Describe the bug**
When you try to 'play' a level, nothing happens.
How can you approve the level?

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a level as a student
2. Click on 'moderate as a teacher and find level'
3. Click button

**Expected behaviour**
The teacher needs to be able to see the level. Let's also add text if they don't need to approve it, as it isn't very clear.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d0d86369-251b-4195-b70e-e50b52d3f503)

**Additional context**
Add Text to explain they only need to view it to check it is okay. no action is needed if it is acceptable. I think?

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
