### ISSUE TITLE
Shortest path for multiple destinations - turn around issues

### ISSUE THREAD

**Issue by MatthewDaggitt** [ocadotechnology/rapid-router#251]
The shortest path algorithm doesn't work for multiple destinations when it requires the van to turn around immediately after reaching a destination. (see diagram below). This is because A\* assumes the van can go backwards without costing fuel, whereas in reality it has to turn around.

![image](https://cloud.githubusercontent.com/assets/2076434/3702218/b24ee51e-13fc-11e4-8fcf-e35999501516.png)

The simplest way to fix this is add a hack to the getOptimalPath method in pathfinder testing whether the van has just come from the node it's going to.

The proper way to fix this is to tie the A\* algorithm into the model and get the model to provide a list of available options for the current situation. (Probably not an A\* algorithm any more). This would support dynamic events in the future such as pieces of road being destroyed.

**Comment by j4mesholland** [comment]
No longer relevant
