### ISSUE TITLE
Change "game" django module to be called "rapidrouter"

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/rapid-router#313]
Not urgent...

**Comment by CelineBoudier** [comment]
We need to think about it at some point... :)

**Comment by j4mesholland** [comment]
To be discussed further with the team, as AI:MMO doesn't use Django for any 'game' elements this isn't a problem right now. If we decide later on to create another game in Django will need to revisit this.

**Comment by faucomte97** [comment]
Unprioritised.
