### ISSUE TITLE
Saving level/similar usability

### ISSUE THREAD

**Issue by josephezammit** [ocadotechnology/rapid-router#393]
So when you save a level, it seems to take a while to process, so it's not good enough to just leave the user waiting until the table updates to show the new level. This is also particularly pertinent when you are updating a level, in which case the table contents of your saved levels *won't* change.

So a "saving..." message/spinning circle/something and then a green tick would probably do the trick here?

**Comment by pawelkrupinski** [comment]
First part superseded by" https://github.com/ocadotechnology/rapid-router/issues/700

**Comment by pawelkrupinski** [comment]
And: #701
