### ISSUE TITLE
Level editor not loading in characters

### ISSUE THREAD

**Issue by MatthewDaggitt** [ocadotechnology/rapid-router#399]

**Comment by faucomte97** [comment]
Reopening this - it seems the issue is present again but specifically with the newly added Electric Van character.

@evemartin I imagine that looking at the fix that's referenced above might give you an idea as to why the Electric Van isn't being loaded in.

**Comment by faucomte97** [comment]
@evemartin Just noticed you've already created #1648 - if you think this is a duplicate then you can just go ahead an re-close it
