### ISSUE TITLE
Too prominent styling

### ISSUE THREAD

**Issue by OliverCartz** [ocadotechnology/rapid-router#465]
The big bold yellow buttons throughout the game are more prominent than arguably more important functions.
e.g. The "Clear Console" button on the python tab stands out far more than the "Play" button

**Comment by j4mesholland** [comment]
This is part of a wider UI issue on Rapid Router and should be revisited. Some work on contextual menus had been started for the iOS project.

**Comment by j4mesholland** [comment]
Work will need to be started on a design system for Rapid Router, but I wanted to make a start with some layout design ideas:

Blockly (level 47 with intro)
![Desktop Blockly 47 instructions.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/9670b8e2-152a-4bfa-bde5-0b5810a4dd44)

Blockly (level 47)
![Desktop Python.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/23b63a74-62da-4c6f-b72e-6466af05e1d0)

Blockly/Python
![Desktop Python_blockly_warning.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/e168594b-600f-4aed-9889-54f598b4cbdb)

![Desktop Python_blockly.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/e812af16-f397-449f-bd2a-ff061aedeaf2)

Python
![Desktop Python.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/c22beeae-c3c3-435a-a888-8d6399041139)

Python showing command list
![Desktop Python_commands.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/0c8761b8-846f-4120-847e-53637fe86504)

**Comment by mrniket** [comment]
Looks much nicer and more consistent with AI:MMO and the portal :) Just wondering about the accessibility/readability of some of the text that is over a purple background? 

E.g.: "Use the python editor below to change your program..."

Would the play button follow material design?

**Comment by j4mesholland** [comment]
Fixed accessibility/readability of some of the text that is over a purple background that was in white previously: _Use the Python editor below to design your program, then click play to try it out!_

![Desktop Python.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/500527fd-f109-465c-848a-7f80b9b36d4f)

**Comment by mariaFernando** [comment]
Looks great!

**Comment by j4mesholland** [comment]
I will close this issue now
