### ISSUE TITLE
Logging off issues for teachers/childrens

### ISSUE THREAD

**Issue by LordyR** [ocadotechnology/rapid-router#472]
Logging off seems to take ages and sometimes we have to get the children to exit the browser as next class ready to come in. This has a knock on effect I think as some children's results say they have taken 7 to 14 days to finish a task which is understandable if they have not been able to log out but it does skew the results. Can you suggest to your developers that scores are only saved once they finish a level. If they don't finish a level and exit, no score is saved.

**Comment by j4mesholland** [comment]
This looks to have been resolved
