### ISSUE TITLE
Make level moderation more user friendly

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/rapid-router#498]
We've had a request for some documentation from a teacher.  Probably better to just make it easier to understand.

**Comment by CelineBoudier** [comment]
@j4mesholland to add to user discovery??

**Comment by j4mesholland** [comment]
Yep, will add it to the list.

**Comment by j4mesholland** [comment]
Some UI could be made to look better, but unsure as to the exact issue. Closing as not sure if it's still relevant post-redesign anyway.
