### ISSUE TITLE
Add rate limiting to all pages

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/rapid-router#511]
On 06/02/2015 we got 75k hits from 13:54 to 14:36 from a single IP address.  This brought one app engine instance to a standstill.  The 75k hits were to /rapidrouter/24.

**Comment by j4mesholland** [comment]
Check if this is still an issue

**Comment by mrniket** [comment]
I think this is still an issue, but the RR level is cached

**Comment by mariaFernando** [comment]
Rapid Router level pages are cached, and there hasn't been any incident in recent years, so this is likely not relevant anymore.
