### ISSUE TITLE
Bree, Sophie and Chris would like a CMS built into the portal

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/rapid-router#519]
Checklist:
- [ ] they can easily make posts
- [ ] posts can include images
- [ ] posts can include code snippets
- [ ] posts can include videos
- [ ] posts can be blogs posts or pages that can be editable
- [ ] they can see previews before pressing go
- [ ] posts can be reduced to teasers
- [ ] posts can be integrated into the front page ala the news items

Nice to have:
- [ ] integrates with the panda

Some Django apps to try:
[Wagtail](http://wagtail.io/)
[Mezzanine](http://mezzanine.jupo.org/)
[Django CMS](https://www.django-cms.org/)
[Fein](http://www.feincms.org/)

**Comment by CelineBoudier** [comment]
copied in portal project
