### ISSUE TITLE
Blocks are loaded outside of the visible area of the workspace

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#533]
When the saved program is too long, some of blocks are displayed outside of the visible workspace.
There's no problem for short programs being loaded.
To reproduce:
Create a long program, then quit the game and re-enter the level that the long program was created in.

Firefox 33.0:
![screenshot from 2015-05-06 14 01 18](https://cloud.githubusercontent.com/assets/11837539/7493483/12bf5fa0-f3f9-11e4-874b-09e022bf3ef1.png)
Google Chrome 41.0.2272.118:
![screenshot from 2015-05-06 14 01 36](https://cloud.githubusercontent.com/assets/11837539/7493484/150d5b04-f3f9-11e4-9594-1a92f6bffda1.png)

**Comment by mtrigueira** [comment]
Setting blocklyBlockCanvas to translate(270.83262634277344,**-123**) by hacking on the dom in chrome seems to work

**Comment by faucomte97** [comment]
Seems to not be relevant anymore
