### ISSUE TITLE
Adding road in level editor

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#544]
Dragging from top down then sideways will always result in the upside down 'L' shape instead of the same path that the cursor was dragged along. Also from bottom to top then sideways

![screenshot from 2015-06-03 15 59 41](https://cloud.githubusercontent.com/assets/11837539/7963673/df5b0abe-0a0b-11e5-9a91-7d5fd6fe2236.png)
![screenshot from 2015-06-03 16 00 50](https://cloud.githubusercontent.com/assets/11837539/7963675/df5eb06a-0a0b-11e5-8136-d6beb4ded8cf.png)

**Comment by j4mesholland** [comment]
No longer relevant
