### ISSUE TITLE
Register as a teacher and independent student with the same email

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#545]
I managed to register as a teacher and also an independent student using the same email address.
Does registering as a independent student only checks for unique username or does it also check for unique email address?

**Comment by faucomte97** [comment]
Will be fixed by https://app.zenhub.com/workspaces/code-for-life-ux-5db8789ca7e95f00017a07df/issues/ocadotechnology/codeforlife-design/56
