### ISSUE TITLE
Emoji passwords

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#546]
Kids can't be relied on to carry around a piece of paper or remember a random password.
Some ideas for improvement:
- Printable list of passwords that teacher keeps
- Letting the children pick their own password (some of them can actually remember and if they forget the teacher can have it printed / written down)
- Low tech - teacher writes the passwords down on a piece of paper

**Comment by CelineBoudier** [comment]
@j4mesholland might be worth keeping that in mind when thinking about the login/registration process, but I'll close this in the meantime.
