### ISSUE TITLE
Check that the route created is short enough to be traversed

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#548]
The following map is not a feasible route as the character will stop half way and run out of fuel.
![screenshot from 2015-06-04 10 33 21](https://cloud.githubusercontent.com/assets/11837539/7981298/e09e022e-0aa5-11e5-8ed9-ead7c655cfb9.png)

**Comment by j4mesholland** [comment]
This is still an issue, needs to be investigated further

**Comment by faucomte97** [comment]
Unprioritised. Feature not bug :)
