### ISSUE TITLE
Prepopulated partial solutions

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#557]
Prepopulated partial solutions (possibly immovable) on some levels, so that students need to fill the missing code.
Can be especially useful when a new concept is introduced, since it can help to guide students in the right direction.

**Comment by Spycho** [comment]
Let's first figure out how we could add levels / episodes / modify existing ones to make use of this, and make sure we are actually adding to the user experience.

**Comment by j4mesholland** [comment]
No longer relevant
