### ISSUE TITLE
Cleanup portal tests

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#568]
Portal selenium tests have messy importing practices (imports before and after classes, partial imports) because of circular dependencies among page classes (unfortunately we can't avoid them).
A way to clean it up might be introducing a page-factory class / module that would contain all the messy imports saving the page classes from unnecessarily messy code.

**Comment by CelineBoudier** [comment]
@PhydeauxLeChien about your test issues...

**Comment by j4mesholland** [comment]
This is still an issue!

**Comment by faucomte97** [comment]
We're migrating to Cypress - see https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/ocadotechnology/codeforlife-portal/979
