### ISSUE TITLE
Cow levels

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#578]
- [x] Applied patch from imperial students
- [x] Updated cow graphics
- [x] Update the scoring algorithm
- [x] Rotate the cow when it's on a vertical road or at a turn
- [x] Fix order of handling events 
- [x] Write help messages
- [x] Move the tree so that the cow will not be on top of it
- [x] Make it more event driven like
  - [x] Change the implementation of the event blocks (does not loop until condition is false, only execute body code once when event occurs)
  - [x] Add sound horn blocks and feature
  - [x] Add puff up blocks and feature
  - [x] Make different cow react to different strategy
  - [x] Condition pauses the animation and makes puff up looks weird
  - [x] highlight event blocks at the same time
- [x] Adding more levels for event handling
- [x] Handle turnaround when enlarged
- [ ] Teaching materials (?)
- [ ] Review the blocks provided for each level
- [ ] Tutorial on how to use the event blocks (video?)
- [ ] Reordering levels
- [ ] Name the levels
- [ ] Fix night mode

Extra features:
- [x] Sometimes after you deleted a cow you cannot select another cow
- [x] Update cow image when another cow type is chosen
- [ ] Make the cow cross the road instead of appearing out of thin air
- [ ] Instructions on using cow in level editor
- [ ] Randomise Jersey cow and normal cow
- [ ] Check in level editor that the origin is at least 3 blocks away from the first cow
- [ ] Add option to enable cow in generating random map in level editor
- [ ] Cannot scale up/down while turning around

**Comment by CelineBoudier** [comment]
Will clean the old features and see later #797
