### ISSUE TITLE
Write test for rest_framework api 

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#593]

**Comment by Spycho** [comment]
Could we get some further info on what this is for please @pawelkrupinski?

**Comment by CheriePun** [comment]
This is a task for writing test for the mobile API (https://www.codeforlife.education/rapidrouter/api/). Currently there's no testing done on that part of the code.

**Comment by Spycho** [comment]
Thanks Cherie!

**Comment by CheriePun** [comment]
I used Django REST framework, this page might be useful for anyone who works on this task (http://www.django-rest-framework.org/api-guide/testing/)

**Comment by j4mesholland** [comment]
This has been done!
