### ISSUE TITLE
Uncaught JavaScript errors

### ISSUE THREAD

**Issue by ruthdw** [ocadotechnology/rapid-router#605]
New most popular error, as logged by GA.  

https://www.codeforlife.education/static/js/foundation.min.js: 2

**Comment by Spycho** [comment]
I think @pawelkrupinski is taking a look at this?

**Comment by CelineBoudier** [comment]
@ruthdw @Spycho any news?

**Comment by Spycho** [comment]
Not sure what state this issue is in I'm afraid.

**Comment by mariaFernando** [comment]
Couldn't replicate this.
