### ISSUE TITLE
Can generate unavailable blocks using the arrow buttons

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#615]
We can generate blocks that are not available in a particular level by using the arrow buttons.

How to reproduce:
1. Go to Level 1
2. Click left arrow button

Even though "turn left" is unavailable on this level, it will be added to the commands list.

![screen shot 2015-08-18 at 09 56 37](https://cloud.githubusercontent.com/assets/304285/9326161/be56732a-458f-11e5-85fb-0d6d3f0bc4b7.png)

**Comment by Spycho** [comment]
I think we decided to not do this.
