### ISSUE TITLE
Less intrusive game messages

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#621]
Currently the messages are only displayed in the huge popup that is modal (doesn't allow anything else to be clicked when it's on), and takes a while to appear and disappear.

Maybe smaller, lighter, more subtle messages popping over the area where the error occured (van, code, etc) might me nicer.

Making the popup appear and disappear instantly would also solve the problem.

**Comment by j4mesholland** [comment]
This is still relevant

**Comment by mrniket** [comment]
I would say that while this is a valid issue, it's still usable and we haven't had any negative feedback recently about this so I'll close it for now. Will reopen if we decide to revisit this issue
