### ISSUE TITLE
Lights are upside down on Level 45

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#625]
<img width="1079" alt="screen shot 2015-08-18 at 12 28 17" src="https://cloud.githubusercontent.com/assets/304285/9328881/a14358ce-45a4-11e5-8c28-18123e1dbcf8.png">

**Comment by dawidchodura** [comment]
@j4mesholland @CelineBoudier Besides solving the case for direction="W", there are a few other options. Should the traffic lights be on the right or left side of the road? Or maybe they could be drawn outside the road?

Option 1: Right side of the road (current)
![trafficlightsright](https://cloud.githubusercontent.com/assets/21366223/18138733/6e0e8818-6fae-11e6-9b99-a4b2a819bb14.png)

Option 2: Left side of the road
![trafficlightsleft](https://cloud.githubusercontent.com/assets/21366223/18138731/6e0c431e-6fae-11e6-8a5d-28856d4c5f84.png)

Option 3: Left side of the road with one of the directions sticking out
![trafficlightsleftaway](https://cloud.githubusercontent.com/assets/21366223/18138732/6e0ce8dc-6fae-11e6-9620-ba2a9a763f2f.png)

Option 4: Right side of the road and west flipped
![trafficlightsrightwestfixed](https://cloud.githubusercontent.com/assets/21366223/18139112/44966c1a-6fb0-11e6-8e24-ba0238f88fd0.png)

Option 5: Left side of the road and east flipped
![trafficlightswestfixed](https://cloud.githubusercontent.com/assets/21366223/18139111/449624c6-6fb0-11e6-96f2-9f94905bb30e.png)

**Comment by dawidchodura** [comment]
Option 6: The red-is-always-above-green option
![allup](https://cloud.githubusercontent.com/assets/21366223/18160396/9ceb0ede-702d-11e6-88ba-e65cb720c3ea.png)

**Comment by j4mesholland** [comment]
Option 6 looks to be the most realistic, except that the bottom red light would be facing me (not to the side).

**Comment by j4mesholland** [comment]
But, that said, the current version is the easiest to understand in actual game play.

**Comment by CelineBoudier** [comment]
i find it more confusing than the current version though... you have to think carefully as to where the traffic lights actually are

**Comment by dawidchodura** [comment]
@j4mesholland I agree that in option 6 the bottom one should be facing the user.

How about lower lights?
![alluplow](https://cloud.githubusercontent.com/assets/21366223/18315577/cafe2006-7517-11e6-92e0-f8db02ea4ad7.png)

**Comment by dawidchodura** [comment]
@CelineBoudier @j4mesholland Current version is Option 1. The lights are upside down in this option. Do you think that we should stay with the current version, so that nothing needs to be changed (in particular level 45)?

**Comment by CelineBoudier** [comment]
Let's keep them like this for the moment - easier to understand
