### ISSUE TITLE
Need to find a good place for Documents folder

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/rapid-router#632]
The Documents folder in deploy has some useful stuff, but mostly only Ocado stuff.  We should move it somewhere better before we open source.

**Comment by Spycho** [comment]
Deploy is no longer a repo. Did it move to portal @pawelkrupinski?

**Comment by CheriePun** [comment]
I believe it's been moved to here in portal (https://github.com/ocadotechnology/codeforlife-portal/tree/master/docs)

**Comment by pawelkrupinski** [comment]
All of deploy is in portal.
Some of these docs (like jump setup) are not useful to open source contributors though, so it makes sense to find a location accessible only to team members.

**Comment by Spycho** [comment]
Thanks both. Let's see if we can move the docs useful to everyone to the wiki, and find somewhere else for the deployment etc. Ocado specific info to live.

**Comment by mrniket** [comment]
No longer relevant
