### ISSUE TITLE
New deployment / release process and project structure

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#658]
How it will work:

Each self-contained functional unit (ocargo, portal, ratelimit, reports, possibly model and test base) will be published separately to public pypi repo. Other modules will depend on a concrete version of the package.

Each package's dependencies will be declared in its setup.py and fetched using pip install (when you install a package it fetches its dependencies).

Deploy project will depend on portal and ocargo to pull them together in order to create a distribution.

Each django project will have its own manage.py and settings.py allowing local development (not used in dev, staging or prod though). Deploy will provide prod settings.

For now we're keeping the projects in portal repo. If that causes problems, we may separate them into separate github repositories.

**Comment by mikebryant** [comment]
I'm making progress on this here: https://github.com/ocadotechnology/codeforlife-deploy-appengine

Currently google appengine is having issues, waiting for them to be resolved: https://code.google.com/p/google-cloud-sdk/issues/detail?id=462#c1
