### ISSUE TITLE
Combine and compress JavaScript files in production

### ISSUE THREAD

**Issue by andersschuller** [ocadotechnology/rapid-router#66]
In order to require fewer requests and speed up page-load.

**Comment by PeterHancock** [comment]
Has using [Browserify](http://browserify.org/) with  [django-pipeline-browserify](https://github.com/j0hnsmith/django-pipeline-browserify) been considered?  With Browserify, browser JS is written as CommonJS modules and then compiled to a single (or more) JS files referenced from the page.  Source map support (turned off in production) makes using Chrome dev tools ,etc, sane whilst configuring a source-watching compilation trigger for rapid development is trivial.  Downsides?  Will probably depend upon NodeJS for development.  Any thoughts?

**Comment by Spycho** [comment]
There's the old pitfall when combining JS files that you can actually harm performance:

Page 1 requires A + B - you bundle A and B into a single file AB and serve that
Page 2 requires A + C - you bundle A and C into a single file AC and serve that
Page 3 requires A + B + C - you bundle A, B and C into a single file ABC and serve that

is worse in terms of total data transferred and latency than:

Page 1 requires A + B - you serve A and B
Page 2 requires A + C - you don't serve A (it's cached in the browser) you just serve C
Page 3 requires A + B + C - you don't serve any JS files (they're all cached in the browser)

It's also debatable how much we should even care about the load times of JS / CSS / images as it should only really matter on the first page load, as subsequent loads of that page should utilise caching. We should determine how much we care about the first page load, given how users use RapidRouter. We obviously still want to make the UX good for new users.

**Comment by CelineBoudier** [comment]
I'm adding @j4mesholland to the loop as well as @SpoonMeiser and @benbacardi .
We do need to choose between switching to these tools, or not using them and then using a python implementation of sass.
We should test the two solutions I think if possible.
And see how it relates in terms of load times for users

**Comment by PeterHancock** [comment]
@Spycho Browserify has an [API](https://github.com/substack/browserify-handbook#partitioning) for factoring out common modules from multiple bundles that should address your concern.  Also, whilst it is debatable whether speeding up load times is always necessary, I think the main advantage of using tools like Browserify is that it encourages splitting up the code base into encapsulated modules without having to reinvent a module system/conventions.  The tricky thing will be incrementally transforming the current code base; with its global vars, scripts loading in a specific order and potentially cyclic dependencies (not yet checked).  It is proving to be challenge for me anyway ;-)

**Comment by CelineBoudier** [comment]
@Knuckles9090 :)

**Comment by CelineBoudier** [comment]
@ruthdw can you please look into this? We had a discussion about webpack instead, it might make sense here as more people in ocado would be able to help?

**Comment by j4mesholland** [comment]
No longer relevant
