### ISSUE TITLE
Tap start block to execute on tablets

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#663]
Test whether the current fix for #619 works on mobile devices.

**Comment by pawelkrupinski** [comment]
I'm going to need a tablet for this one.

**Comment by CelineBoudier** [comment]
It doesn't work on an IPad Air on Safari nor on my Samsung Galaxy 3.
However, it does seem weird that a simple click would execute the program on a mobile device: a badly timed drag and drop could trigger it unexpectedly...
I also talked with a UX expert in Ocado and she told me it was a weird feature anyway...

**Comment by mrniket** [comment]
Still an issue

**Comment by faucomte97** [comment]
Deprioritised.
