### ISSUE TITLE
2FA hides password reset

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#684]
Steps to reproduce on a 2FA enabled account:
1. Got to /teach/, enter login details and click "Sign in".
2. When the token form appears, go back to teach and click "Forgotten Password?" link

You'll end up back at teach and the url will change to "/teach/?next=/teach/home/"

It seems that if 2FA login process is pending, the password reset screen gets redirected back to /teach/.

**Comment by CelineBoudier** [comment]
This is because after the sign in attempt, the teacher is no longer "not_logged_in" because a UserProfile has been found. This issue should be in the portal project, I will close it and open a new one there.
