### ISSUE TITLE
Find a good way of automatically prepending our licence to all files

### ISSUE THREAD

**Issue by Spycho** [ocadotechnology/rapid-router#687]
There must be a fairly standard way of doing this, as it must be a very common issue for open source projects. @mikebryant or the rest of the open source community may know? I suspect there's a git pre-commit hook out there that would do the trick.

**Comment by jishi9** [comment]
If we can't find a ready solution, one way would be to have 1) a unit test
that verified the licence is in-place in all files, and have that run as a
pre-commit hook , and 2) a simple bash/python script that prepends the
license to files that don't have it

**Comment by eddarmitage** [comment]
This seems like the issue most related to my comment on #704. As stated there, I think we should certainly add a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) file to provide some indication of our requirements and expectations.

**Comment by eddarmitage** [comment]
If we do have a unit test that verified the license was in place, and we ran our tests on something like travis, we could probably hook it into the [status API](https://github.com/blog/1935-see-results-from-all-pull-request-status-checks) to give us some traffic lights for whether or not we're ok to merge.

If you fail the test (having claimed to have read the CONTRIBUTING.md), you'll get a red light, you add a commit with the necessary licenses, the tests re-run, turning everything green, and you're good to go.

If we're going to require developers agree to a CLA, we could do something similar with [clahub](https://www.clahub.com/).

**Comment by mikebryant** [comment]
I'm working on hooking it into Travis - that'll all be hooked automatically into the status api :)

**Comment by mikebryant** [comment]
I think the best place for this might be in something like https://codeclimate.com/ - we could contribute an engine to do license checks, maybe using Apache's RAT (Release auditing tool - the thing they use to check for licensing etc.)

**Comment by mrniket** [comment]
No longer relevant
