### ISSUE TITLE
Make turn around animation smoother

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#690]
At the moment turn around manoeuvre  consists of 3 distinct animations with easings: easeIn, linear, linear. That means the van stops abrubtly at the end of the third animation.
Sequence of easeIn, linear, easeOut results in a visible change of speed between 2nd and 3rd manoeuvre.
Figure out the maths and calculate durations that result in smooth movement.

**Comment by mrniket** [comment]
Still an issue but not fixing
