### ISSUE TITLE
Improved JavaScript error reporting

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#693]
Current JS error reporting solution (errors published to Google Analytics) doesn't give us stacktraces which limits our debugging possibilities.

Possible solutions:
http://www.stacktracejs.com/#!
https://trackjs.com/

Since we're running out of fields to piggyback information on, we might consider persisting the errors in the database and having a simple reporting page. Some stacktrace libraries might help us with that as well (displaying the errors / stacktraces).

**Comment by ruthdw** [comment]
New Relic also provides basic trace information.  It's not as full-featured as the other two, but I've found it at least give you enough information to reproduce the bug and inspect it properly.

**Comment by faucomte97** [comment]
Deprioritised.
