### ISSUE TITLE
Speed control (Fast Forward) is sluggish

### ISSUE THREAD

**Issue by javicg** [ocadotechnology/rapid-router#694]
The functionality seems to have regressed on recent changes.
The van moves is small jumps, instead of in a fluid motion.

**Comment by pawelkrupinski** [comment]
That's intended - in the slow mode the easing makes it feel more natural - the van accelerates and decelerates gradually with each manoeuvre. The pause was (re)introduced to make it easier to follow the program and associate movement with specific code.
In the fast mode these things are not that useful, but I think it makes sense to keep it consistent just for the sake of not increasing complexity of that code.

**Comment by javicg** [comment]
Ah, I see.
Makes sense, although I found it strange the first time I saw it (I always work without sound though; maybe with the sound of the animation it's better).
I will close the issue.
