### ISSUE TITLE
Improve UX of left panel in game

### ISSUE THREAD

**Issue by Spycho** [ocadotechnology/rapid-router#696]
UX input needed. Hold off on the implemented but disabled feature of clicking save / load again taking you back to workspace. Probably instead do something like making the workspace be the "default" thing you see, tab it at the top for the Blockly and Python levels, and make all other buttons on the left panel that need to show content do a slide out or popup like "help" does.

**Comment by lauracumming** [comment]
Issue moved to [ocadotechnology/codeforlife-design #1](https://github.com/ocadotechnology/codeforlife-design/issues/1) via [**ZenHub**](https://www.zenhub.com/)
