### ISSUE TITLE
Speed up game screen loading time

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#703]
The request takes 400-600ms to return (in prod).
The whole page takes about 2s to show the popup (in prod).

**Comment by mrniket** [comment]
Still an issue

**Comment by mrniket** [comment]
Perhaps look at loading the rest of the script asynchronously (via `defer`)?

Also could be interesting to look at using service workers to make this a progressive web app

**Comment by lauracumming** [comment]
Is this still an issue?

**Comment by faucomte97** [comment]
@lauracumming no.
