### ISSUE TITLE
Optimise attempt submission (defer to scoreboard for data aggregation)

### ISSUE THREAD

**Issue by javicg** [ocadotechnology/rapid-router#728]
At the moment, we are storing all attempts in the DB, marking the best for each level (to speed up generation of the scoreboard).
The data is stored on a single table, and it's growing considerably fast.

A better implementation would be to move the best attempts to a separate table, that could be used to generate the dashboard.

**Comment by javicg** [comment]
After discussing with @mikebryant it seems a better approach would be:
- Delegating the responsibility of determining which attempt is the best for a given level and student to the scoreboard generator (remove the necessity for a "best_attempt" flag).
- Remove the flag and leave the submission code simple and fast

**Comment by mrniket** [comment]
Needs investigation

**Comment by faucomte97** [comment]
Deprioritised.
