### ISSUE TITLE
Mocking locally SMTP server

### ISSUE THREAD

**Issue by Mati20041** [ocadotechnology/rapid-router#744]
Running locally server, without configuring SMTP server, causes django to crash on user registration.

**Comment by eddarmitage** [comment]
I believe that at some point @ruthdw had django running in such a configuration that emails were logged to the console. Perhaps she can shed some light on this?

**Comment by CelineBoudier** [comment]
We tried to have the emails logged in the console, but it still crashed (python -m smtpd -n -c DebuggingServer localhost:1025)
The settings were probably off, there's some doc here: https://docs.djangoproject.com/en/1.9/topics/email/
