### ISSUE TITLE
Some strings aren't externalized

### ISSUE THREAD

**Issue by piotrrepetowski** [ocadotechnology/rapid-router#760]
I have noticed that we have many hardcoded strings in the project.

Many of them are in game/templates/*_/_.html

**Comment by piotrrepetowski** [comment]
The below commit is only a part of the required work.

**Comment by piotrrepetowski** [comment]
Not sure what is the purpose of "Django migr text" from game/templates/game/level_editor.html? :smile:

**Comment by CelineBoudier** [comment]
@piotrrepetowski Yes there are a lot of strings in messages.js, but some are hardcoded in the HTML files. There is overall an inconsistent use of string management. For instance the popup function which takes in parameter a title, a subtitle, a description etc - all parameters might be in messages.js, while at some other times the title only will be in messages.js and the other hardcoded at function call. 

I think overall this can be improved, while not necessary for localisation, it would be cleaner.

**Comment by mrniket** [comment]
Stale, if we find strings that aren't externalised, we will make make separate new issues for it
