### ISSUE TITLE
Mute button reverts on next level (and doesn't mute Blockly noises)

### ISSUE THREAD

**Issue by benbacardi** [ocadotechnology/rapid-router#766]
It'd be better if the mute button honoured your choice through the levels, rather than reverting to unmuted each time.

Also, it'd be good if it could mute the noises Blockly makes as you drag/drop the blocks around.

**Comment by ChrisMukherjee** [comment]
Ok, so I've fixed the main issue. The mute button now stays muted between levels. Will look into fixing the Blockly sounds via issue #802.

**Comment by mikebryant** [comment]
You should use the `Urls` object provided by `django-js-reverse`. (I believe this is already being loaded)
There's no need to have a settings variable for the rapid-router path.
