### ISSUE TITLE
Improve the setup instructions

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/rapid-router#776]
The setup instructions in the readme are not clear enough when installing from scratch.
We need to improve this for users, depending on their OSs

**Comment by PhydeauxLeChien** [comment]
Is there anything more to do for this, that wasn't covered in #798, #800?

**Comment by CelineBoudier** [comment]
Looks fine so far - however later on I'd also like better instructions for Mac users (and a working Windows run ^^)

**Comment by mrniket** [comment]
Stale
