### ISSUE TITLE
run says Can't find msguniq

### ISSUE THREAD

**Issue by mtrigueira** [ocadotechnology/rapid-router#777]
On OSX

> $./run
> CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.

This is because of missing file translation/localization 

Work around:

> brew install gettext
> (Presumably on Ubuntu apt-get install gettext)

Alternative work-around:
comment out line 2 of run

> # set -e

**Comment by mtrigueira** [comment]
Related to #776

**Comment by CelineBoudier** [comment]
@mtrigueira Would you like to improve the readme, for mac users? So far it's very linux oriented :)
(cc @PhydeauxLeChien @mzywiol @j4mesholland )

**Comment by mrniket** [comment]
Not relevant
