### ISSUE TITLE
A newline character in a translation string can break a JS string

### ISSUE THREAD

**Issue by piotrrepetowski** [ocadotechnology/rapid-router#784]
Steps to reproduce:

1. Set locale to pl
2. Try to open https://staging-dot-decent-digit-629.appspot.com/rapidrouter/1/

The cause:
In the translation string there is the new line character which breaks the JS string.

I think we could use escapejs filter to fix the error, but I'm not sure whether we can have more generic solution.

What do you think?

**Comment by mikebryant** [comment]
`escapejs` looks like the right solution for this to me - it's for exactly this usecase

**Comment by mikebryant** [comment]
Looks like this is fixed :)
