### ISSUE TITLE
Change orientation of the arrows next to the Go button

### ISSUE THREAD

**Issue by rwawryk** [ocadotechnology/rapid-router#787]
How about changing orientation of the arrows next to the Go button depending on van's position? Current layout is correct when van is heading north, but after turning right (i.e. heading east) the arrows should be rotated clockwise by 90 degrees.
Or maybe it is feature to make children to think in 2D?

**Comment by CelineBoudier** [comment]
adding @j4mesholland 
This is an interesting point. I believe that we can see it different ways. Should the arrow represent the objective direction like North, South, East, West like now, or should it display the subjective direction for the van?
(Regarding 2, I'm afraid the arrows rotating as the van moves might be dizzying??)

**Comment by j4mesholland** [comment]
I worry that rotating the arrows would just add to the confusion. They should need to think about what they are doing. I will do a mockup so that we can see, then we can decide what's best.

**Comment by j4mesholland** [comment]
Mockup: [RapidRouter-App-arrowrotate.pdf](https://github.com/ocadotechnology/rapid-router/files/277289/RapidRouter-App-arrowrotate.pdf)

**Comment by wulmer** [comment]
I prefer the fixed button direction as it more closely resembles the scripting commands. IMHO clicking on the *left* arrow should always add a "move *left*" command.

**Comment by j4mesholland** [comment]
Lets just stick with the arrows the way they are. Niket has been working on an AR version of RR which will solve the issue for really young players. Also if the teachers use the unplugged activity sessions this explains how they need to think about directions.
