### ISSUE TITLE
Localisation of the "Go" button

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/rapid-router#790]
The English "Go" word is hardcoded in the button to play the game in the first levels of Rapid router.
It is a problem for localisation.

(We should figure a way to change the button from an image (especially since Go is not that easily translatable in Polish, the language we're currently translating the game in) )

@piotrrepetowski

**Comment by CelineBoudier** [comment]
![screenshot from 2016-05-24 14-21-05](https://cloud.githubusercontent.com/assets/8862062/15505571/f8eb3328-21bb-11e6-815c-99983f8f100b.png)

**Comment by j4mesholland** [comment]
How about a play arrow button instead?

**Comment by CelineBoudier** [comment]
yes!

**Comment by j4mesholland** [comment]
![go](https://cloud.githubusercontent.com/assets/18662916/15507113/1f5f5d6c-21c2-11e6-95b0-9ea73a60239e.gif) Something like this? @CelineBoudier @OneGreenPlanet @sophinlondon @piotrrepetowski

**Comment by piotrrepetowski** [comment]
Yes, this is something I was thinking about.

**Comment by piotrrepetowski** [comment]
@j4mesholland Can we use the button or maybe this was just a proposition?

**Comment by CelineBoudier** [comment]
Would like to talk to @OneGreenPlanet (Bree) about this :)

**Comment by j4mesholland** [comment]
hi @piotrrepetowski, Bree is happy for us to use this play button in place of the 'Go'. Do I just need to replace here: rapid-router/game/static/game/image/actions/go.svg

**Comment by piotrrepetowski** [comment]
@j4mesholland Yes, I think so.

**Comment by piotrrepetowski** [comment]
We forgot about the texts. What do you think about this:

![screen-1](https://cloud.githubusercontent.com/assets/2862360/22129954/764fb9ec-dea9-11e6-880f-e9edec903f4d.png)
![screen-2](https://cloud.githubusercontent.com/assets/2862360/22129959/7acd2b3a-dea9-11e6-808b-6fda864aeed4.png)

@CelineBoudier @j4mesholland

**Comment by CelineBoudier** [comment]
My opinion: yes, with proper alt text for accessibility :)
@j4mesholland ?

**Comment by j4mesholland** [comment]
Yes I agree. Should we also put the start icon in as well?
![add-icons-to-instructions](https://cloud.githubusercontent.com/assets/18662916/22148646/3be561ea-df07-11e6-89de-6d3c0c9f85c5.png)

**Comment by CelineBoudier** [comment]
Yes it would be more consistent!

**Comment by piotrrepetowski** [comment]
That's a great idea. I think we can focus here on the former Go button and create another issue for replacing other texts with icons (we should use blockly block just to be able to translate them).

What do you think?

**Comment by CelineBoudier** [comment]
Yes it sounds good - but then I'll create either an issue with a checklist or several issues for the other icons :)

**Comment by piotrrepetowski** [comment]
That's fine with me :)
