### ISSUE TITLE
UX for review

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#793]
Compiling all UX/UI issues for Rapid Router

## Description
We have some historical issues about the shortcomings of the existing game UI.

**We will need to build a design system:**
- Colours 
- Fonts
- Buttons
- Menus
- Overlays

As well as considering the other issues in this epic.

**Comment by j4mesholland** [comment]
Priorities to be reviewed

**Comment by mrniket** [comment]
@j4mesholland please refine
