### ISSUE TITLE
Random road tests are incomplete

### ISSUE THREAD

**Issue by faucomte** [ocadotechnology/rapid-router#842]
Tests for the random road generator only test for branchiness and curviness, not size, loopiness or scenery.

**Comment by faucomte** [comment]
Tests now include size and scenery. Curviness and loopiness are still not covered.

**Comment by mrniket** [comment]
Still relevant

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/842?planning-poker) with Zenhub @faucomte97 @SKairinos

**Comment by faucomte97** [comment]
Closing this as we need to fix & improve the random road generator feature.
