### ISSUE TITLE
Solve button raises error when pressed in custom levels

### ISSUE THREAD

**Issue by faucomte** [ocadotechnology/rapid-router#843]
When a teacher plays a custom level, pressing the 'Solve' button generates this error:
'Could not connect to server. Your internet might not be working properly.'

This is caused by the fact that there is no recorded solution for custom levels for the solve button to find.
To solve this, the creator of the level could be required to provide the solution to their level for it to be saved and retrieved later, or the Solve button could just be removed altogether.

**Comment by CelineBoudier** [comment]
@j4mesholland any idea on how to better fix this? Was thinking about just removing the solve button for the custom levels at least for the moment.
