### ISSUE TITLE
[Polish only] traffic lights don't do anything

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/rapid-router#848]
In levels 47 and 48, if you set your django-language cookie to pl-pl, the:
repeat until zielone światło as well as the
repeat while światło czerwone
don't do anything, ie the van just stops.
It works fine in English though.

**Comment by piotrrepetowski** [comment]
@CelineBoudier I'm closing this as it was fixed in #854 (I made a mistake in the commit message).
