### ISSUE TITLE
The Scoreboard feature doesn't work properly for some languages

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/rapid-router#870]
If you set your browser / django language cookie to Slovakian or Polish, you can't display the scoreboard for several levels for instance.
A Slovakian teacher also had a timeout when exporting several levels on Firefox.

When the django_language is set to English or French, it works fine.

**Comment by CelineBoudier** [comment]
@piotrrepetowski https://docs.djangoproject.com/en/1.8/topics/i18n/formatting/#std:templatefilter-unlocalize
might do the trick!

**Comment by piotrrepetowski** [comment]
Will check, thanks!

**Comment by piotrrepetowski** [comment]
Looks that did the trick.
