### ISSUE TITLE
Remove extra padding in CSS that is causing items to drop

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#911]
Please remove the extra padding which is causing some elements to drop down the page.
Also on the videos, the white border is a larger depth than the actual video

![screen shot 2017-05-25 at 11 17 27](https://cloud.githubusercontent.com/assets/18662916/26446437/e8389c1e-413b-11e7-9cf7-62e21498fce6.png)

![screen shot 2017-05-25 at 11 17 37](https://cloud.githubusercontent.com/assets/18662916/26446544/69de3ae4-413c-11e7-9ad8-f66c797f1c92.png)

![screen shot 2017-05-25 at 11 21 39](https://cloud.githubusercontent.com/assets/18662916/26446525/578451ee-413c-11e7-8d7c-6aececb22a24.png)

**Comment by faucomte** [comment]
Created on Rapid Router project instead of portal. Made redundant by issue 496 in portal.
