### ISSUE TITLE
Link to API key on Crowdin project settings page doesn't work

### ISSUE THREAD

**Issue by wulmer** [ocadotechnology/rapid-router#920]
When trying to get the crowdin project API key as mentioned in the README, the page shows an error that this page is not accessible. It seems like the project settings page is not accessible for normal users.

Is there a way to share the project's API key somehow?

**Comment by piotrrepetowski** [comment]
Hi wulmer, can you elaborate why you need API key?

I'm affraid the API key cannot be shared publicly.

**Comment by wulmer** [comment]
Hi @piotrrepetowski , I think it was a misunderstanding of the current [README](https://github.com/ocadotechnology/rapid-router/blob/master/README.md). It was mentioned there that for localization, you need the crowdin API key.
In the meantime, @CelineBoudier has created a PR (#923) which improves the README by explaining that this API key is only needed for localization admins.
I will close this issue then.
