### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hosamaly** [ocadotechnology/rapid-router#928]
There are some issues with RTL support. I'll try to collect some of them in the comments.

**Comment by hosamaly** [comment]
In the Level Editor, the welcome modal dialog is forcing strings to be rendered from left to right. This causes punctuation marks to appear at the wrong end of the sentence.

Additionally, having English words in the middle of the text (e.g. `%(help_label)s`) causes the sentence to be reversed.

Here is an example of how the page currently looks like:
![LTR modal with RTL text](https://user-images.githubusercontent.com/330633/28933607-93c67c52-7875-11e7-858d-76887f2878f5.png)

And here is how it should look like:
![RTL modal with RTL text](https://user-images.githubusercontent.com/330633/28933630-b2aa8adc-7875-11e7-888c-471bf63dbfcc.png)

(This effect was achieved by adding `direction: rtl` to `#myModal`.)

**Comment by mrniket** [comment]
Not a priority atm but I'll keep this issue open.

**Comment by faucomte97** [comment]
Deprioritised.
