### ISSUE TITLE
Arabic font support

### ISSUE THREAD

**Issue by hosamaly** [ocadotechnology/rapid-router#929]
The current fonts (Helvetica Neue, Source Sans Pro, etc.) do not always contain the full set of Unicode characters, thus causing the browser to fall back to the system's "Sans Serif" font for rendering Arabic characters.

Although this works, it doesn't give the same feeling. For example, the fonts may look playful and cheerful in English but they look formal in Arabic.

The solution, in my opinion, is to be able to specify a different set of fonts based on the user's language. Here is an example of different Arabic fonts:
https://fonts.google.com/?subset=arabic

**Comment by hosamaly** [comment]
In the Google Fonts page, I think the font "Mada" is the one that somehow resembles how my kids would write. :)

**Comment by CelineBoudier** [comment]
Thanks for this @hosamaly, sounds good, @j4mesholland what is your font-loving opinion? :)

**Comment by mrniket** [comment]
Not a priority atm but I'll keep this issue open.

**Comment by faucomte97** [comment]
Deprioritised.
