### ISSUE TITLE
Build scoreboard page

### ISSUE THREAD

**Issue by faucomte** [ocadotechnology/rapid-router#931]

**Comment by CelineBoudier** [comment]
The branch that @faucomte started: https://github.com/faucomte/rapid-router/tree/redesign-scoreboard (thanks in advance @ruthdw )
The idea is that the form itself didn't work properly if I'm not mistaken

**Comment by ruthdw** [comment]
@CelineBoudier Task is a _tiny_ bit thin on detail!

**Comment by CelineBoudier** [comment]
Yes. I thought the mockups were there - @j4mesholland can you put your mockup there?

**Comment by j4mesholland** [comment]
Mockup is here:
https://marvelapp.com/2d66a83/screen/30733630

**Comment by j4mesholland** [comment]
@ruthdw  did you manage to make any progress with this?

**Comment by j4mesholland** [comment]
This is now live on production
