### ISSUE TITLE
Add app manifest

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/rapid-router#945]
https://developers.google.com/web/fundamentals/web-app-manifest/

**App icon:** @j4mesholland to add RR app icon in svg format...

**URL** When the app starts up the user will be directed to this URL: https://www.codeforlife.education/rapidrouter/

**Splash screen** background color: #A0C53A
logo here:![Rapid-Router-logo.svg](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/884ef0c8-f1ef-4e2f-a374-ef9306facb5d)

**theme color:** #4A4A4A

**initial orientation:** landscape

**no app banner yet (we want to test first)**

**Comment by j4mesholland** [comment]
iOS app icon here: 
![rr-ios-icon](https://user-images.githubusercontent.com/18662916/38322114-6af29ee2-3831-11e8-8f7c-92fb46c820fa.png)

**Comment by j4mesholland** [comment]
and a 512x512px version: 
![rr-ios-icon-512x512px](https://user-images.githubusercontent.com/18662916/38322733-2e7683e6-3833-11e8-9e35-2190d82c22d2.png)

**Comment by Luk3s** [comment]
We are working on this branch https://github.com/ocadotechnology/rapid-router/tree/add_app_manifest

**Comment by j4mesholland** [comment]
Updated icon
![rr-ios-icon-512x512px](https://user-images.githubusercontent.com/18662916/38636580-83655ff2-3dc0-11e8-8926-9bdf46197169.png)

**Comment by j4mesholland** [comment]
in sizes: 192 & 384
![RR-iOS-Icon_192x192.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/56f1e4de-6c2a-46a4-8ca4-6fef11b703bf)

![RR-iOS-Icon_384x384.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/6084fd37-472b-4987-8e09-e7787d63eb2f)
