### ISSUE TITLE
Hit box on map/code window is too small

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#948]
We could have something like this:
![Screen Shot 2018-03-28 at 16.59.04.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/5759fcdb-d6f9-4f33-a944-8501a87b6ff5)

**Comment by j4mesholland** [comment]
Voulunteer task?

**Comment by mrniket** [comment]
Not a priority, closing this issue.
