### ISSUE TITLE
Only some level names have punctuation

### ISSUE THREAD

**Issue by cgarcia-ocado** [ocadotechnology/rapid-router#965]
Just for consistency, but I guess they should all follow the same rule ;)

**Comment by j4mesholland** [comment]
For example:

<img width="1180" alt="screen shot 2018-08-10 at 17 00 55" src="https://user-images.githubusercontent.com/18662916/43968416-ed434b52-9cbe-11e8-92d5-4f5883de905f.png">

**Comment by piotrrepetowski** [comment]
I think it depends on grammar (or writing) rules. For instance in Polish you omit a full stop, while question and exclamation mark are ok.

Not sure how it works in English. I've found something regard that https://www.proof-reading-service.com/en/blog/full-stops-titles-headings-captions/

**Comment by mrniket** [comment]
@piotrrepetowski Agreed :) We should remove the full stops.
