### ISSUE TITLE
Rapid Router Student dashboard - Prototypes

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#969]
## Description ##
Create prototypes of the new design wireframes of the student dashboard (play/details/)

## Acceptance criteria ## 
- [x] Use Marvel App (https://marvelapp.com/) to create the prototypes
- [ ] Create a questionnaire or moderated user test process for metrics

## Metrics ##
- [x] Ask for feedback from at least two users (preferably children).
- [x] Collate results

**Comment by j4mesholland** [comment]
Use Marvel App to create the prototypes: https://marvelapp.com/

**Comment by j4mesholland** [comment]
Please review: https://sketch.cloud/s/Dddry/PO35Q8/play

**Comment by faucomte97** [comment]
Looks good to me @j4mesholland :)

**Comment by CelineBoudier** [comment]
@j4mesholland I can't see the dropdown you had added? Else it's :fire:

**Comment by j4mesholland** [comment]
The dropdown should work now. Please try this other link:
https://sketch.cloud/s/3GDWo/9k0YOP/play

**Comment by CelineBoudier** [comment]
LGTM

**Comment by faucomte97** [comment]
Dropdown works but there could maybe be an extra option on top to allow users to go back to the student dashboard page without having to use the browser back button :)
