### ISSUE TITLE
Localisation in level selection page doesn't fully work

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#985]
**Describe the bug**
When using Crowdin in context with Rapid Router, the episode names and level names do not show in the language they're supposed to, even if they've already been translated. This is because the html content is not in a `{% blocktrans %}` block.

**To Reproduce**
Steps to reproduce the behaviour:
1. Access Crowdin within the Rapid Router website.
2. Navigate to the level selection page.
3. Observe that it is not possible to translate the episode names and level names into any language.

**Expected behaviour**
Crowdin should allow us to translate/view what has already been translated when it comes to these strings. These should be included in the html translation blocks.

**Screenshots**
![localisation](https://user-images.githubusercontent.com/33633200/47568974-5a33d400-d92a-11e8-9a0f-1175a9a45a03.png)

The chosen language here is French. The buttons in the header and the episode ranges are successfully translated, but it is not possible to translate the episode names or the level names.

**Desktop (please complete the following information):**
All

**Comment by faucomte97** [comment]
**Update**: It seems like this issue only affects the episode names now.

**Comment by piotrrepetowski** [comment]
I think I've found another reason for this issue:

1. Episode names and level titles are cached.

2. Because of the 1 it might happen that English labels are returned even though CrowdIn mode was enabled.

3. Having English labels cause that CrowdIn JS library is not able to mark them as translatable.
