### ISSUE TITLE
All teachers of a school can see all classes in the scoreboard

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/rapid-router#997]
**Describe the bug**
when accessing the scoreboard on Rapid Router, as a teacher I can see all classes of the school, regardless of my status as head teacher or not

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.codeforlife.education/rapidrouter/scoreboard/
2. look at the class list on selected classes. they're all here

**Expected behaviour**
to only see my own classes, and maybe all the school classes if I'm an admin teacher only

**Screenshots**

**Desktop (please complete the following information):**
 - windows 10, chrome 

**Additional context**

**Comment by mrniket** [comment]
needs investigation

**Comment by sebp999** [comment]
To reproduce on local machine: 
- Make an admin teacher.  
- Make some classes for that teacher.  
- Make another teacher at the same school.  Log in as that teacher.
- Make a class for that teacher.
- Go to scoreboard.  All classes for the school are shown, not just the ones that belong to the currently logged in non-admin teacher.
